### ISSUE TITLE
feat: Add support for header and path provider state generators in Rust Consumer.

### ISSUE THREAD

**Issue by MajorCaiger** [pact-foundation/pact-reference#103]
Hi

Working on a big Pact project for one of our clients and one of their services is written in Rust. We noticed that some of the functionality we required was missing from the Rust Consumer library, such as header from provider state, and path from provider state.

I've raised a PR for the functionality (https://github.com/pact-foundation/pact-reference/pull/102) but it's my first PR into this project and my first time writing Rust so if someone could review it and give feedback that would be great.

**Comment by uglyog** [comment]
You Rust changes were good, nothing too worry about there :-D

Closing this as it has been merged.

**Comment by MajorCaiger** [comment]
Thanks @uglyog . I'm glad it was ok.

Can I ask, do you have a release cycle for the consumer library? Or do you have an ETA when this change might be released?

Thanks

**Comment by uglyog** [comment]
I'll schedule a release shorty, but there is no release schedule, it as needed.

**Comment by uglyog** [comment]
0.7.6 has been released
