### ISSUE TITLE
Response Headers Forced to Lower Case

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#112]
If you set up a response header on a consumer interaction which contains capital letters then the actual response from calling the mock server has the header in all lower case.

For example, when testing the PactNet integration:

```csharp
bool response = server.ResponseStatus(interaction, (ushort)HttpStatusCode.Created)
             && server.WithResponseHeader(interaction, "X-Response-Header", "value1", 0)
             && server.WithResponseHeader(interaction, "X-Response-Header", "value2", 1)
             && server.WithResponseBody(interaction, "application/json", @"{""foo"":42}");
```

then calling the mock server, this fails with:

```
Xunit.Sdk.XunitException
Expected result.Headers {[Access-Control-Allow-Origin, System.String[]], [Access-Control-Allow-Headers, System.String[]], [Access-Control-Allow-Methods, System.String[]], [Access-Control-Expose-Headers, System.String[]], [x-response-header, System.String[]], [Date, System.String[]]} to contain [X-Response-Header, System.String[]].
```

Note how the response header is a different case between the setup and actual response.

We should instead preserve the casing that the user specified. HTTP headers aren't supposed to be case sensitive but it's still unexpected that the mock server doesn't return exactly what you told it to return.

**Comment by uglyog** [comment]
The headers are being setup as per the pact file, but it is the underlying server implementation that is changing the headers. With a quick test, I can see
```
06:41:05 [INFO] Received request Request ( method: GET, path: /mallory, query: Some({"status": ["good"], "name": ["ron"]}), headers: Some({"host": ["127.0.0.1:40071"], "user-agent": ["curl/7.74.0"], "accept": ["*/*"]}), body: Empty )
06:41:05 [INFO] comparing to expected Request ( method: GET, path: /mallory, query: Some({"status": ["good"], "name": ["ron"]}), headers: None, body: Missing )
06:41:05 [INFO] Request matched, sending response Response ( status: 200, headers: Some({"Content-Type": ["text/html"], "X-Response-Header": ["value1", "value2"]}), body: Present(28 bytes, text/html) )
```

The headers are the correct case. After a little digging in the Hyper server code, I found:
> This function expects the input to only contain lowercase characters. This is useful when decoding HTTP/2.0 or HTTP/3.0 headers. Both require that all headers be represented in lower case.

So it looks like it is on purpose to support HTTP/2.0
