### ISSUE TITLE
Feature: Formatting a randomly generated UUID

### ISSUE THREAD

**Issue by surpher** [pact-foundation/pact-reference#121]
RandomUUID ExampleGenerator is only writing a simple UUID, eg: `22fa4d123c17471bbb6ab57aaa5fb24f` into a Pact file. This makes it a bit annoying when expecting uppercased and/or dash separated value and can fail automatic serialisation.

Would be nice to have an optional argument to pass in that would define what format to return the UUID in. (eg: .simple, .lowercasedDashed, .uppercasedDashed,...)

Original issue describing the context can be found at https://github.com/surpher/PactSwift/issues/70

**Comment by uglyog** [comment]
Formats are:
* simple `936DA01f9abd4d9d80c702af85c822a8`
* lower-case hyphenated `936da01f-9abd-4d9d-80c7-02af85c822a8`
*  upper-case hyphenated `936DA01F-9ABD-4D9D-80C7-02AF85C822A8`
* URN `urn:uuid:936da01f-9abd-4d9d-80c7-02af85c822a8`

**Comment by surpher** [comment]
Just to confirm, PactSwift implemented this and it seems to be working 👍
