### ISSUE TITLE
compiler error building pact_mock_server_cli could not find `json_utils`

### ISSUE THREAD

**Issue by crunchy-vonage** [pact-foundation/pact-reference#124]
> cargo install pact_mock_server_cli

`error[E0432]: unresolved import `pact_matching::models::json_utils`
  --> /Users/matthew.churcher/.cargo/registry/src/github.com-1ecc6299db9ec823/pact_mock_server_cli-0.7.4/src/verify.rs:11:28
   |
11 | use pact_matching::models::json_utils::json_to_string;
   |                            ^^^^^^^^^^ could not find `json_utils` in `models``

**Comment by uglyog** [comment]
I've released 0.7.5 which is fixed
