### ISSUE TITLE
nom 6.x is incompatible with regex

### ISSUE THREAD

**Issue by audunhalland** [pact-foundation/pact-reference#128]
`nom 6.2.x` pins `memchr` to `<2.4.0`: https://github.com/Geal/nom/issues/1330

This causes problems together with [regex](https://docs.rs/regex), which transitively requires `memchr ^2.4.0`.

`tree_magic_mini` also requires `nom 6`, so that lib will also need an update.

This issue is blocked until `nom` gets a new major release. I will keep an open eye and create a PR here when things are ready.

**Comment by Geal** [comment]
you can now upgrade to nom 7, which separates regex parsers in the nom-regex crate and removes the version pinning for memchr

**Comment by audunhalland** [comment]
PR upgrading nom in `tree_magic_mini`: https://github.com/mbrubeck/tree_magic/pull/3

**Comment by markdingram** [comment]
Hi - I see this is merged now - would it be possible to release a new version of the "pact_consumer" crate that would pick up these changes? Many thanks

**Comment by uglyog** [comment]
0.7.8 has been released
