### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by AssafKatz3** [pact-foundation/pact-reference#14]
Is it possible to create docker images of these projects? Espcially of CLI

**Comment by uglyog** [comment]
Good idea! I'll get onto that.

**Comment by AssafKatz3** [comment]
I worked on it, it will be in my fork (https://github.com/AssafKatz3/pact-reference) in next hours. But helping will be very welcome since this is the first time that I do something like this.

**Comment by AssafKatz3** [comment]
Hi,
I added the modifications (adding of release-docker.sh and Dockerfile files) - https://github.com/pact-foundation/pact-reference/compare/master...AssafKatz3:master. I need help for integrate to build.
Thanks,
Assaf

**Comment by AssafKatz3** [comment]
The code is pulled from my fork, but still don't intergrate to build process. I don't know how to write it, and don't have permission to grant docker hub to [automated builds on Docker Hub
](https://docs.docker.com/docker-hub/builds/).

**Comment by uglyog** [comment]
I've setup access to pact foundation docker hub, so I'll setup the repo as soon a I get a spare moment.

**Comment by uglyog** [comment]
Docker images exists at:

* https://hub.docker.com/r/pactfoundation/pact-ref-mock-server/
* https://hub.docker.com/r/pactfoundation/pact-ref-verifier/
