### ISSUE TITLE
feature: support disabling and providing custom SSL certificates

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-reference#144]
We currently support it for the provider but not the broker itself. I think we should:

1. Support disabling SSL for the broker interactions
2. Support specifying custom certificate paths for the broker and the verifier (ideally supporting the OpenSSL convention of the `SSL_CERT_FILE` and `SSL_CERT_DIR` environment variables).

See https://github.com/pact-foundation/pact-js/issues/736 for background, it may already be partially supported through the reqwest dependencies.

**Comment by abatkin** [comment]
I believe the issue is that the `reqwest` dependency uses the `rustls-tls` feature which uses `webpki-roots` (basically a vendored certificate store, always ignoring anything about the local system's configuration). The proper fix would be to switch to pulling `rustls-native-certs` which will do the right thing (same rules as openssl on Linux, use schannel on Windows, security-framework on MacOS).

**Comment by uglyog** [comment]
The problem was due to supporting musl based distributions like Alpine, we switched from openssl to rustls-tls. As long as rustls-native-certs does not require openssl, we can try use that.

**Comment by abatkin** [comment]
Another option would be a top-level feature (which can at least be selectable on the CLI) for deciding what to do (whether that feature is turning musl-compatibility on or switching to native certs is up to you). I understand the desire to make lightweight/static builds easy/possible, but ignoring system standards makes using/supporting tools very difficult.

For companies that use intercepting proxy servers (a lot of companies) or anyone who has internal PKI infra (which lets companies issue certificates for internal services), you can't currently use these pact tools unless you completely disable certificate verification.

**Comment by mefellows** [comment]
Is this all that is needed? It looks like there is now an Alpine specific feature flag that can be enabled, but not sure it works like that: https://github.com/pact-foundation/pact-reference/pull/149

**Comment by mefellows** [comment]
hmm the segfault says otherwise: https://github.com/pact-foundation/pact-reference/pull/149/checks?check_run_id=3647761625#step:3:663

**Comment by uglyog** [comment]
That change was to use the platform TLS support, which means linking to the openssl libs on Linux. We don't want that.

What we need is either to be able to use the Rust TLS support, but use the system root certs (which I assume is what rustls-native-certs does, but I haven't looked into it.), or we need a compile time feature flag to only use Rust TLS when building on Alpine Linux. It can't be a runtime flag (like a CLI switch).

**Comment by uglyog** [comment]
The other option would be to drop Alpine support, which will make a lot of things easier, but anger a lot of people. :-D

**Comment by mefellows** [comment]
I was hoping that adding `native-tls-alpn` (the alpine variant) magically would work. 

Now that I look at the [options](https://docs.rs/reqwest/0.11.4/reqwest/index.html#optional-features) again, it looks like `rustls-tls-native-roots` might be what we want?

![Screen Shot 2021-09-20 at 1 23 49 pm](https://user-images.githubusercontent.com/53900/133954252-ed883e8e-6687-4786-b9d2-dfc3674ee7b3.png)

**Comment by mefellows** [comment]
That PR passed now - does that mean it just works ™️ ?

**Comment by uglyog** [comment]
That means it's compiling, on Alpine, which is 90% of the battle :-D

But it doesn't test access to a broker using TLS and custom supplied root certs.

**Comment by abatkin** [comment]
I pulled and built the branch locally. It correctly picks up our enterprise root certificates and can now connect to an endpoint that was previously inaccessible.

(This is Linux with regular glibc, not musl)

**Comment by uglyog** [comment]
That works for me. If it builds on musl, I'm sure it will behave in the same way.

**Comment by mefellows** [comment]
Just tested on my OSX env by importing (and trusting) the baddssl certificates into the keychain - works a treat (much better than an env var, obviously).

**Comment by abatkin** [comment]
For some reason certificate verification still isn't working for me on Windows, will keep you posted

**Comment by abatkin** [comment]
I take it back - this works on Windows (the server I was testing against was misconfigured and wasn't sending the intermediate certificate)
