### ISSUE TITLE
Support port range in RUST implementation

### ISSUE THREAD

**Issue by AssafKatz3** [pact-foundation/pact-reference#15]
Currently as far as I understand, there is no limit about port range that can be passed

**Comment by AssafKatz3** [comment]
Hi,
The actual requirmenet is creation of static export in docker file from issue #14 .
Thanks,
Assaf

**Comment by uglyog** [comment]
Aah, yes, we will need that.

**Comment by uglyog** [comment]
I have modified your implementation to scan for the next available port, in case there is something else with a port open in the range. It will now skip over those.
