### ISSUE TITLE
Support asynchronous message pacts in pact-consumer

### ISSUE THREAD

**Issue by mervyn-mccreight** [pact-foundation/pact-reference#155]
Similar as described in https://github.com/pact-foundation/pact-reference/issues/73 it would be nice to be able to define message pacts on consumer side.

Unfortunately there seems to be just an `InteractionBuilder` for `RequestResponeInteraction`, but a similar implementation for `Message` is missing.

If I am just missing how to do it, I'd be very happy for a hint in the right direction :)

**Comment by uglyog** [comment]
I've already started adding message support (for Protobuf). It is on the feat/plugins branch. You can see an example test using it here: https://github.com/pact-foundation/pact-plugins/blob/main/examples/protobuf/protobuf-consumer-rust/src/lib.rs#L25 (it is a Protobuf test, but it will work for any message format)

This week we will be looking to progress the plugin work from a prototype, which will mean releasing the Rust libs. 

If working with the beta versions is a problem, we can look to backport the changes to master.

**Comment by uglyog** [comment]
v0.8.0-beta.0 is released with the MessageInteractionBuilder

**Comment by mervyn-mccreight** [comment]
Thanks! I'll have a look at it :)
