### ISSUE TITLE
Linux and Windows FFI 0.0.3 Have Different Internal Versions

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#157]
Pact files generated from Windows and from Linux have different Pact metadata using FFI 0.0.3.

In Windows it's 0.1.3:

```json
  "metadata": {
    "pactRust": {
      "version": "0.1.3"
    },
    "pactSpecification": {
      "version": "3.0.0"
    }
  },
```

On Linux it's 0.1.5:

```json
  "metadata": {
    "pactRust": {
      "version": "0.1.5"
    },
    "pactSpecification": {
      "version": "3.0.0"
    }
  },
```

We have some integration tests which verify the pact file output and they are passing on Windows but failing on Linux because of the mismatch:
https://github.com/pact-foundation/pact-net/runs/3825949419?check_suite_focus=true#step:8:1905

The version also appears to have gone significantly backwards. It used to be 0.9.x and now it's 0.1.x

**Comment by uglyog** [comment]
That version is the version of the library that wrote the pact file (pact-models). It is concerning that the version is different.

Before the big refactor where the FFI libraries got merged, it would have been the version of the pact matching FFI lib. But it makes sense to set it to the FFI lib version.

**Comment by adamrodger** [comment]
Closing as no longer relevant
