### ISSUE TITLE
Feature: release arm artifacts

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-reference#160]
arm is becoming a popular runtime, we should support arm based artifacts / CLI tools.

See https://github.com/pact-foundation/pact-js-core/issues/347 for background.

**Comment by andytson-inviqa** [comment]
and it will perform better on Apple Silicon than dockerised amd64, considering Apple has dropped Intel

**Comment by mmoll** [comment]
Is there any update on this? The current Rust based beta of pact-js is still failing to install in Linux/arm64.

**Comment by mefellows** [comment]
If you have any proposals on how we can add an arm build we are all ears. GitHub actions doesn't yet support arm and we don't have access to an arm machine to run the builds on. 

Amazon hasn't yet approved our access to use their arm instances to use as a GH hosted agent.

**Comment by rholshausen** [comment]
We already have aarch64 artifacts (Apple M1), which are cross-compiled on the OSX agents.

What other arm targets would we need to support?

**Comment by andytson** [comment]
linux arm64 artifacts, some people need to use docker desktop on Apple M*, and x86_64 emulation in docker can have problems with interoperability with other software needed in the same image.

Github Actions can use docker buildx to provide emulation in qemu if cross-compilation not possible directly. The artifacts can then be exported from the images.

**Comment by mefellows** [comment]
For docker, you should be able to use `--platform linux/amd64`. See above, until we have a reliable way to compile for linux arm64 we can't produce shared modules.

**Comment by andytson** [comment]
as I said, this is when needing pact in the same image as other software, so that other software would have to be stable and performant on emulation, which it often isn't

**Comment by mefellows** [comment]
> Github Actions can use docker buildx to provide emulation in qemu to build targets if cross-compilation not possible directly. The artifacts can then be exported from the images.

Ah, sorry I missed this bit.

PR welcome :)

**Comment by rholshausen** [comment]
Just a quick note on cross-compiling, we are using the onig library to have compatible regular expressions with the original Ruby version of Pact. Onig requires a C compiler, so setting up cross compiling is a lot harder to do than with just Rust code (which seems to work ok).

**Comment by rholshausen** [comment]
Looks like cross-compiling using [cross](https://github.com/cross-rs/cross) works.

```
pact-reference/rust/pact_ffi on  feat/arm64 [?] is 📦 v0.3.6 via △ v3.22.1 via 🦀 v1.62.1 
❯ cross build --target  aarch64-unknown-linux-gnu
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.3
   Compiling quote v1.0.21
   Compiling syn v1.0.99
   Compiling libc v0.2.129
   Compiling autocfg v1.1.0
.
.
.
    Finished dev [unoptimized + debuginfo] target(s) in 38.94s

pact-reference/rust/pact_ffi on  feat/arm64 [?] is 📦 v0.3.6 via △ v3.22.1 via 🦀 v1.62.1 took 1m 
❯ ls -l ../target/aarch64-unknown-linux-gnu/debug/
total 1120356
drwxr-xr-x 39 ronald ronald      4096 Aug 15 11:57 build
drwxr-xr-x  2 ronald ronald     69632 Aug 15 11:58 deps
drwxr-xr-x  2 ronald ronald      4096 Aug 15 11:57 examples
drwxr-xr-x  6 ronald ronald      4096 Aug 15 11:58 incremental
-rw-r--r--  2 ronald ronald 724354670 Aug 15 11:58 libpact_ffi.a
-rw-r--r--  1 ronald ronald      2894 Aug 15 11:58 libpact_ffi.d
-rw-r--r--  2 ronald ronald  96193140 Aug 15 11:58 libpact_ffi.rlib
-rwxr-xr-x  2 ronald ronald 326599104 Aug 15 11:58 libpact_ffi.so

pact-reference/rust/pact_ffi on  feat/arm64 [?] is 📦 v0.3.6 via △ v3.22.1 via 🦀 v1.62.1 
❯ file ../target/aarch64-unknown-linux-gnu/debug/libpact_ffi.so 
../target/aarch64-unknown-linux-gnu/debug/libpact_ffi.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e8dc754d62f3a6fa1ff8e7a1ba85fc6cef6725d8, with debug_info, not stripped
```

I'll see if this works with the GitHub actions, but it should because it uses docker images to provide the target build environments.

**Comment by rholshausen** [comment]
Confirmed the cross-compiled library works with Pact-JS using an Ubuntu aarch64 VM on QEMU

**Comment by mefellows** [comment]
Awesome - thanks! I'll create a tracking item for JS and Golang to implement.
