### ISSUE TITLE
Rust `pact_consumer` API does not provide all features & could be more idiomatic

### ISSUE THREAD

**Issue by emk** [pact-foundation/pact-reference#17]
Hello! Thank you for such an interesting testing tool. We'd love to use this to test the interaction between some Rust and JavaScript services at work.

However, after playing around with the Rust `pact_consumer` library a bit, I found a number of issues which make it difficult to use. Here's a partial list:

1. The code in the documentation doesn't seem to work when used with the released version of the library. I'm not sure what's going on here.
2. The use of `s!("string")` everywhere is not idiomatic Rust. This could be replaced with `Into<String>` arguments, which would allow passing either `&str` or `String` types without any problem. This is a pretty easy fix.
3. The high-level `pact_consumer` API provides no obvious support for matchers. This could be implemented using arguments of the type `Into<PactPattern>`, or something similar, allowing the passing of `&str`, `String`, `regex::Regex`, `like(value)` and `serde_json::Value`.
4. The `body` and `headers` APIs make it unnecessarily verbose to handle the common case, which is a 200 + JSON response. This could be made more ergonomic.
5. It's currently hard to reuse the same interaction in multiple test cases, at least in my experience, even if it's identical.
6. Probably some other things I'm not thinking about right now.

This is a fairly long wishlist! So I propose handling this as follows:

- I'm going to go ahead and fork `pact_consumer`, and do a major API overhaul in my branch.
- If you like the code I write, you're 100% welcome to merge it upstream into `pact_consumer`!
- If you're not interested in my changes, I'm happy to maintain them as a separate Rust Pact V2 client.

**Comment by emk** [comment]
If you're interested, you can see my work-in-progress on the https://github.com/faradayio/pact-reference/commits/rust_api_ideas branch.

I have no idea whether you'll want any of this, of course. :-) But I'll do my best to make an interesting Rust consumer API, and hopefully it will at least give you some ideas.

**Comment by mboudreau** [comment]
@emk Love your tenacity.  We haven't had a lot of resources on this project yet and has mostly been @uglyog doing all the work, sadly.  The idea is to create a single Rust codebase for our whole specification across all versions and build a shared C library for each OS, which we can then thinly wrap other languages around it.  

As I'm sure you noticed, we have several branches of the different specs, but a lot is left to be desired before this library is complete and we can then use it as the core that runs all our Pact libraries.  Since none of us are Rust experts, we definitely appreciate any recommendations and contributions you may have.

Cheers.

**Comment by emk** [comment]
@mboudreau Thank you! I'm mostly focusing on `pact_consumer`, which hasn't changed much between V2 and a new V3 branch. Basically, I'd love to help bring the Rust consumer testing up to par with Ruby and JavaScript (we use all three at work).

But before I tackle that seriously, I do have one important question: How complete is the `pact_matching` crate in Rust? Does it actually implement the specification in a reasonably complete and correct fashion? (I'm not worried about the high-level API here, which is easy enough to tweak, just the actual low-level algorithm.)

Anyway, one of my first challenges was getting the "doctests" in `pact_consumer` to actually run every time the tests run. This would ensure that the code in the documentation is an actual, working example. (In the master branch, this is disabled because the doctest uses `#[test]`, which actually means that the example code is ignored.)

It turns out that there may be an issue with how `cdylib` and `doctest` work together in Cargo. At the request of the Cargo maintainers, I've filed a bug upstream here: https://github.com/rust-lang/cargo/issues/4567

While they're looking at that, I'm going to switch to using regular unit tests instead of doctests, and work on my API proposals.

**Comment by uglyog** [comment]
@emk more than happy to include any PR! All the help would be appreciated.

The `pact_consumer` crate was written to test the interaction with the pact broker, so it is very basic at the moment.

The `pact_matching` is complete (with respect to V2 spec) and the V3 branch is probably 80% done. I think it is only missing an implementation of generators.

As to `s!` macro, please feel free to replace that.

**Comment by emk** [comment]
OK, thank you! I've opened a PR at #18 with my preliminary & ongoing work. It's not ready to merge yet, but I'll move further discussion there and close this issue.

Thank you for inviting me to hack on your code and propose ideas!
