### ISSUE TITLE
Verifier FFI Passes on OSX When it Should Fail

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#176]
See pact-net CI run here: https://github.com/pact-foundation/pact-net/runs/4964627047?check_suite_focus=true

I've written an integration test which invokes the FFI with some non-existant pact sources (like a URI source to `example.org`) and it also never starts a provider. The verification should fail because of the missing source, and also because the provider is missing.

On Windows and Linux the test passes (as in, the verification fails, as expected), but on OSX the verification succeeds. It can't possibly succeed though, because there's no provider running.

**Comment by uglyog** [comment]
I can see the verification has failed in the test output:

```
Failures:

1) Failed to load pact - Failed to load pact 'http://example.org/file.json' - Request failed with status - 404 Not Found

2) Failed to load pact - Could not load pacts from the pact broker 'http://broker.example.org/' - IoError("Failed to access pact broker path '/' - error sending request for url (http://broker.example.org/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known. URL: 'http://broker.example.org/'")
```

How is the test checking for the result of the verification?

**Comment by adamrodger** [comment]
If it gets a non-zero return code from the FFI call then it's considered to
have failed, then PactNet throws an exception.

I can't run it under the debugger because I don't have a Mac, but given it
works on Windows and Linux that must mean it returns zero on OSX even when
it fails...?
