### ISSUE TITLE
MinType Matchers Breaking Change With Ruby Behaviour

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#178]
The "min type" matchers in the Rust library don't behave the same as the ones from the Ruby library, in a breaking way.

In PactNet 3.x (backed by Ruby) and 4.x (backed by Rust) you can create a consumer tests which uses a min type matcher like this:

```cs
Match.MinType("foo", 1);
```

i.e. you pass it a single example value and the minimum allowed number of elements in the response array. This serialises to something like this for Ruby:

```json
{
    "json_class": "Pact::ArrayLike",
    "contents": "foo",
    "min": 1
}
```

and like this for Rust:

```json
{
    "pact:matcher:type": "type",
    "value": "foo",
    "min": 1
}
```

When you called the mock server for Ruby, the response that comes back is an array with the example value inside

```
["foo"]
```

but the Rust version just sends back the single value, not wrapped in an array:

```
"foo"
```

This is a big breaking change for all of our consumer tests when upgrading to a library which uses the Rust code, and one which I think we should fix to make work the same as the Ruby version.

**Comment by mefellows** [comment]
You just need to wrap the value in an array, i.e.

```
{
    "pact:matcher:type": "type",
    "value": ["foo"],
    "min": 1
}
```

**Comment by adamrodger** [comment]
Two problems I see with that:

1. Every library maintainer has to do that, whereas the idea with the core library is that those common behaviours are managed centrally
2. There's a potential ambiguity created across different languages. If PactNet starts wrapping those but PactGo or PactJS doesn't then moving between different languages isn't a consistent experience.

I think the core library should be standardising on that, hence raising the ticket here instead of simply working around it in PactNet.

**Comment by mefellows** [comment]
Maybe. It doesn't feel like as big an issue to me.

The matcher seems to do what it says - i.e. it's a type matcher, so it matches on the type it was given.

Ruby has `"json_class": "Pact::ArrayLike",` for an array type, and "Pact::SomethingLike" for non-array types, so perhaps if we want to make the mapping more obvious we should have a `pact:matcher:type: "type"` and `pact:matcher:type: "array"`. But, personally, I also felt it was weird that there was a specific type for arrays and the others just got "SomethingLike.".

Maybe I'm missing something about underlying assumptions here? I think one is that there is a 1:1 mapping of what was in Ruby and is now in Rust, which is probably fair.

**Comment by adamrodger** [comment]
The problem is that there's years of existing experience where people expect that you pass a single example item to a mintype matcher and the mock server gives you an array with that item back.

We want to keep that behaviour because it's a huge pain for people upgrading otherwise. The thought of having to go and change the hundreds of places that exists now... No thanks 😂

So, given that we want to keep it, but the core doesn't support it, we've got 2 choices

- the simple choice - use the core to standardise so we only implement it once and it's always correct. We write tests which ensure this is always the case.
- the complex one - rely on every library to implement that behaviour in exactly the same way, with all the different people and all the different languages being consistent without anything to enforce that. We can't write a test which checks every language like that.

Given one option is clearly way more complex and risky than the other, I'd vote for the simple and safe one.

That's the benefit of having a core library over everyone implementing it separately in their own languages - we implement it once and then every library is the same, with central tests to ensure we don't break it.

**Comment by mefellows** [comment]
> The problem is that there's years of existing experience where people expect that you pass a single example item to a mintype matcher and the mock server gives you an array with that item back.
> We want to keep that behaviour because it's a huge pain for people upgrading otherwise. The thought of having to go and change the hundreds of places that exists now... No thanks 😂

Oh, of course I agree with that. But am I missing something complicated? In Pact Go and Pact JS, that's just implementation detail and how a Matcher is serialised to JSON and passed to the core. The public facing matcher API still looks the same.
