### ISSUE TITLE
Feature: Implement CustomHeaders handling 

### ISSUE THREAD

**Issue by fabio-andre-rodrigues** [pact-foundation/pact-reference#182]
When writing provider tests in pact-net 3.x.x  (that used the Ruby Implementation) we had the option to define CustomHeader manipulation. That was a useful feature, because in that way we could easily handle authentication token being invalid without having to use middleware to change requests on the fly.

Such implementation would then be called in other implementations that uses this one as the base for.

Thanks in advance

**Comment by mefellows** [comment]
Thanks!

**Comment by uglyog** [comment]
@mefellows just adding these to the HTTP client as default headers. This means that the headers will also be included on any state change call. I assume this is the same with the Ruby implementation.

**Comment by uglyog** [comment]
Pact FFI 0.2.3 released
