### ISSUE TITLE
Add `x86_64-unknown-linux-musl` target

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#185]
Note that this is a Tier 2 supported platform for Rust though, not Tier 1:
https://doc.rust-lang.org/rustc/platform-support.html#tier-2-with-host-tools

**Comment by uglyog** [comment]
musl does not support loading shared libraries. So while we can use the x86_64-unknown-linux-musl target, it can only produce a static library (.a extension) and not a shared library (.so, .dylib or .dll).

**Comment by uglyog** [comment]
0.2.3 now has a musl artifact [libpact_ffi-linux-x86_64-musl.a.gz](https://github.com/pact-foundation/pact-reference/releases/download/libpact_ffi-v0.2.3/libpact_ffi-linux-x86_64-musl.a.gz)
