### ISSUE TITLE
rust/pact_matching: OptionalBody::Present should take Vec<u8> instead of String

### ISSUE THREAD

**Issue by emk** [pact-foundation/pact-reference#19]
While working on https://github.com/pact-foundation/pact-reference/pull/18, I found one minor API tweak that might be useful. The `OptionalBody::Present` constructor uses a `String` to represent HTTP request and response bodies. In Rust, `String` always represents a valid UTF-8 string (and this is strictly enforced, on pain of undefined behavior). But it's useful to be able to test against binary HTTP bodies such as images.

The easiest way to do this would be to modify `OptionalBody::Present` to hold a `Vec<u8>` instead of a `String`. This is not an urgent feature request for us, so there's no reason we would need to consider this for V2. I'd also be happy to talk through any design issues or Rust implementation challenges which come up.

**Comment by emk** [comment]
Now that I've learned a lot more about Pact internals, I can see that this basically isn't going to happen, because everything serializes down to JSON, and there's no way to represent binary strings in JSON. Probably we should just chalk this up to "unavoidable limitations"? Feel free to close this.

**Comment by uglyog** [comment]
Binary strings can be stored in Base64 format in the JSON file, so it is possible to implement this.

**Comment by uglyog** [comment]
I've confirmed that when generating the JSON, if the body fails to convert to a UTF-8 string, it gets written in base64 format.
