### ISSUE TITLE
WhiteSource Security Check raising vulnerabilities

### ISSUE THREAD

**Issue by surpher** [pact-foundation/pact-reference#192]
A WhiteSource security check has been run on a project using https://github.com/surpher/PactSwift. The report exposed vulnerabilities mostly dealing with transient dependencies' used versions:

| Dependency hierarchy | Severity | Vulnerable Library | Suggested Fix |
| --- | --- | --- | --- |
| `pact_matching-0.4.1.crate` -> `regex-0.2.10.crate` -> `thread_local-0.3.5.crate` | high | `thread_local-0.3.5.crate` | Upgrade to version `thread_local - 1.1.4` |
| `pact_matching-0.4.1.crate` -> `hyper-0.9.18.crate` -> `rustc-serialize-0.3.24.crate` | high | `rust_serialize-0.3.24.crate` | |
| `pact_matching-0.4.1.crate` -> `hyper-0.9.18.crate` -> `traitobject-0.0.1.crate` | high | `traitobject-0.0.1.crate` | |
| `pact_matching-0.4.1.crate` -> `hyper-0.9.18.crate` | high | `hyper-0.9.18.crate` | Upgrade to `hyper-0.14.10.crate` |
| `pact_models-0.2.1.crate` -> `reqwest-0.11.5.crate` -> `tokio-rustls-0.22.0.crate` -> `tokio-1.12.0.crate` | medium | `tokio-1.12.0.crate` | Upgrade to `tokio-1.8.4,1.31.1` |
| `pact_models-0.2.1.crate` -> `chrono-tz-0.5.3.crate` -> `parse-zoneinfo-0.3.0.crate` -> `regex-1.5.4.crate` | medium | `regex-1.5.4.crate` | Upgrade to version `regex - 1.5.5` |
| `pact_matching-0.4.1.crate` -> `hyper-0.9.18.crate` -> `cookie-0.2.5.crate` | medium | `cookie-0.2.5.crate` | Upgrade to version `0.7.6` |
| `pact_models-0.2.1.crate` -> `chronot-tz-0.5.3.crate` -> `chrono-0.4.19.crate` | low | `chrono-0.4.19.crate` | |

The latest crate version should be used where possible and in `pact-reference/rust`s control.

**Comment by rholshausen** [comment]
Closing this as none of those versions are used anymore
