### ISSUE TITLE
Publish Verification Results from URL Sources

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#199]
(See https://github.com/pact-foundation/pact-net/issues/392 for more info)

### Problem

Currently the FFI only exposes options to publish results for pacts retrieved from the broker. The code to publish results takes a `PactSource` and only publishes with one of the broker variants:

https://github.com/pact-foundation/pact-reference/blob/23c0c593157ea63497a3731878b0bc4f875e8fd0/rust/pact_verifier/src/lib.rs#L1207-L1228

In the [Ci/CD Setup Guide](https://docs.pact.io/pact_nirvana) we recommend creating a verification step in CI which is triggered from a webhook containing the URL of a pact when it changes. This would then use the URL source to pull and verify the pact, but you then also want it to publish the results back. Currently this isn't possible with URL sources.

### Proposed Solution

We should inspect the pact file itself and see whether it contains a link for publishing verification results. If it does, and the user has asked to publish results, then the link within the pact file should be used. That would make it agnostic of whether the file was retrieved from a broker source or a URL source, and would still be safe against non-broker URL sources (thanks @bethesque for pointing me in the right direction for that).

That way the [`pactffi_verifier_set_publish_options`](https://github.com/pact-foundation/pact-reference/blob/23c0c593157ea63497a3731878b0bc4f875e8fd0/rust/pact_ffi/src/verifier/mod.rs#L260) function is truly independent of the source used and instead relies on the pact contents themselves.

Authentication for publishing the results is still possible because both `pactffi_verifier_url_source` and `pactffi_verifier_broker_source` supply credentials.

### Example

For example, if you run the Pact Broker Docker image and inspect the example pact, you will receive:

```json
{
  "consumer": {
    "name": "Example App"
  },
  "provider": {
    "name": "Example API"
  },
  "interactions": [ ... ],
  "_links": {
    "self": {
      "title": "Pact",
      "name": "Pact between Example App (5556b8149bf8bac76bc30f50a8a2dd4c22c85f30) and Example API",
      "href": "http://localhost:9292/pacts/provider/Example%20API/consumer/Example%20App/version/5556b8149bf8bac76bc30f50a8a2dd4c22c85f30"
    },
    "pb:publish-verification-results": {
      "title": "Publish verification results",
      // 👇👇👇 this is the verification link
      "href": "http://localhost:9292/pacts/provider/Example%20API/consumer/Example%20App/pact-version/cc79bbc141aa53a4fd45d155d705cbb243dec4b6/verification-results"
    }
  }
}
```

**Comment by adamrodger** [comment]
From a quick read through of the code, I think the publishing side supports this but the bit that's currently missing is that the links aren't parsed from the pact file when using the URL source.

If the links were parsed from the JSON and added as a field to `PactSource::URL` then the `publish_results` pattern match could also support URL sources. From that point forwards it already uses the publish results link so everything would be fine, it's just that currently URL resources don't have that link parsed/attached and thus aren't supported.

There'd have to be some internal refactoring because currently a lot of the code to parse things out of the pact live in the `pact_broker` module, whereas actually they need to be a bit more abstract than that. There should be a function for pulling pacts from the broker and another for pulling pacts from a URL source, then after that the code can be agnostic of the source and work only on the pact content itself.

That way if the pact has the verification link then we simply publish results to it, without needing to know where the pact file came from.

I'd do it myself but I really struggle to read the Rust code given the current non-standard formatting (2 space tabs and incredibly dense code with very long lines). I had to read the code locally after doing a `cargo fmt` with standard settings so that I could read it, which obviously then means I can't submit changes back.

**Comment by xeroeugene** [comment]
I can see https://github.com/pact-foundation/pact-reference/blob/9a6c846f3eae42f9123bf02efb44053e1e8a2f12/rust/pact_verifier/src/lib.rs#L1059-L1063 has been merged to master. Was this release yet?

**Comment by rholshausen** [comment]
The verifier crate (0.13.8) and verifier CLI (0.9.11) have been released with this fix, but the FFI library still needs to be released.

**Comment by YOU54F** [comment]
Thanks for the excellent write up and proposal Adam. Fully in support and on board with this. 

@rholshausen has the FFI been released yet? I don't quite understand what is involved in releasing it, and the impact to libraries consuming it, so if you have some time or docs to point me in the direction of that would be great.

And on this point

> I'd do it myself but I really struggle to read the Rust code given the current non-standard formatting (2 space tabs and incredibly dense code with very long lines). I had to read the code locally after doing a cargo fmt with standard settings so that I could read it, which obviously then means I can't submit changes back.

I checked the contributor guide and there is nothing on code formatting and the rational. would a section in the contributing guide to be good, as it may have saved you a job here, if Adam was able to do it himself, and I trust he would have made sure it was solid for pact-net and other libs 👍🏾 

Fab work all

**Comment by rholshausen** [comment]
@YOU54F we can release it, but we need to test the logging output before we can upgrade Pact-Net to 0.3.x version.

**Comment by xeroeugene** [comment]
Since ffi [has been released](https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.3.3), can this issue be closed now? 

.net side has corresponding issue https://github.com/pact-foundation/pact-net/issues/392
