### ISSUE TITLE
Need to provide more info when a pact merge conflict occurrs

### ISSUE THREAD

**Issue by uglyog** [pact-foundation/pact-reference#2]
When there is a merge conflict, the consumer test fails with something like

```
expected to be equal to <PactVerified>, got <PactError("Unable to merge pacts, as there were 1 conflict(s) between the interactions")>
```

**Comment by YOU54F** [comment]
Is this still required or can it be considered complete?

https://github.com/pact-foundation/pact-reference/commit/118daa1f96ef2fb46268febb1972a25377cc08c0

There were some improvements in the above commit to provide more granular information on mismatches.

It looks like we collect errors and report back 

message pact errors - https://github.com/pact-foundation/pact-reference/blob/5699cab757e31875b74ea8ce98cd9821dc331421/rust/pact_models/src/message_pact.rs#L341

sync pact errors - https://github.com/pact-foundation/pact-reference/blob/5699cab757e31875b74ea8ce98cd9821dc331421/rust/pact_models/src/sync_pact.rs#L325

do we need to do the same in the v4 merge func

https://github.com/pact-foundation/pact-reference/blob/118daa1f96ef2fb46268febb1972a25377cc08c0/rust/pact_matching/src/models/v4/mod.rs#L547-L558
