### ISSUE TITLE
rust/pact_matching generates { "match": "type", "min": "1" } instead of { "match": "type", "min": 1 }

### ISSUE THREAD

**Issue by emk** [pact-foundation/pact-reference#20]
This means that pacts build using `rust/pact_consumer` can't actually be used to verify providers written in other languages.

This is caused by the representation of `Matchers`:

```rust
/// Data structure for representing a collection of matchers
pub type Matchers = HashMap<String, HashMap<String, String>>;
```

### Possible fix 1: Use JSON

It's tempting to change this to:

```rust
/// Data structure for representing a collection of matchers
pub type Matchers = HashMap<String, HashMap<String, serde_json::Value>>;
```

...but this causes an endless nightmare of issues with `PartialEq` versus `Eq`, because JSON can technically contain floating point numbers, and floating point numbers have (thanks to the IEEE) a nonstandard definition of `==` and `!=`. This is to avoid Rust hitting this [horrifying Python bug](https://news.ycombinator.com/item?id=9090228):

```python
  >>> nan = float('nan')
  >>> xs = [1, nan, 0, 3, 5, 2]
  >>> sorted(xs)
  [1, nan, 0, 2, 3, 5]
```

And of course, Rust _cares_ about this issue and it wants us to care, too. This ultimately means that `serde_json::Value` only supports `PartialEq` and not `Eq` or `Hash`. But we need `Matchers` to support `Eq` and `Hash`, so we want to keep floating point types well away from it.

### Possible fix 2: Make our own custom `enum`

We could do something like this:

```rust
#[derive(Debug, PartialEq, Eq, Hash)]
enum StringOrUsize {
    String(String),
    Usize(usize),
}

pub type Matchers = HashMap<String, HashMap<String, StringOrUsize>>;
```

But this feels like it's just sweeping the problem under the rug, and of course it requires a huge number of code changes, and it's going to keep growing new `enum` values.

### Possible fix 3: Use parsed `Matcher` objects

We actually have a high-level type representing `Matcher` objects, so we could just write:

```rust
pub type Matchers = HashMap<String, Matcher>;
```

...and upgrade `Matcher` to a public type with all the traits we want, maybe something like:

<details><summary>Implementation sketch here</summary><div>

```rust
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Matcher {
    Equality,
    Regex(Regex),
    Type,
    MinType(usize),
    MaxType(usize),
}

impl<'de> Deserialize<'de> for Matcher {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>
    {
        // All possible fields which may appear in a matcher's JSON.
        #[derive(Debug, Deserialize)]
        #[serde(deny_unknown_fields)]
        struct AllFields {
            matches: Option<String>,
            regex: Option<String>,
            min: Option<usize>,
            max: Option<usize>,
        }

        // Use serde to deserialize our data.
        let parsed = AllFields::deserialize(deserializer)?;

        // Helper function: Assuming that we have either a `min` or a `max`
        // clause, parse it.
        let parse_min_max_type = || {
            if let Some(min) = parsed.min {
                Some(Matcher::MinType(min))
            } else if let Some(max) = parsed.max {
                Some(Matcher::MaxType(max))
            } else {
                None
            }
        };

        // Interpret our data.
        match parsed.matches.as_ref().map(|m| &m[..]) {
            Some("equality") => Ok(Matcher::Equality),
            Some("regex") => {
                let regex_str = parsed.regex.as_ref().ok_or_else(|| {
                    D::Error::custom(
                        "\"regex\" matching rule must have key \"regex\""
                    )
                })?;
                let regex = Regex::new(regex_str).map_err(|err| {
                    let msg = format!(
                        "could not parse regular expression {:?} - {}",
                        regex_str,
                        err,
                    );
                    D::Error::custom(msg)
                })?;
                Ok(Matcher::Regex(regex))
            }
            Some("type") => {
                Ok(parse_min_max_type().unwrap_or(Matcher::Type))
            }
            Some(matches) => {
                let msg = format!("unknown matching rule of type {:?}", matches);
                Err(D::Error::custom(msg))
            }
            None => {
                parse_min_max_type().ok_or_else(|| {
                    let msg = format!("unsupported matching rule {:?}", parsed);
                    D::Error::custom(msg)
                })
            }
        }
    }
}

impl Serialize for Matcher {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
        where S: Serializer
    {
        match *self {
            Matcher::Equality => {
                let mut map = serializer.serialize_map(Some(1))?;
                map.serialize_entry("matches", "equality")?;
                map.end()
            }
            Matcher::Regex(ref regex) => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("matches", "regex")?;
                map.serialize_entry("regex", regex.as_str())?;
                map.end()
            }
            Matcher::Type => {
                let mut map = serializer.serialize_map(Some(1))?;
                map.serialize_entry("matches", "type")?;
                map.end()
            }
            Matcher::MinType(min) => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("matches", "type")?;
                map.serialize_entry("min", &min)?;
                map.end()
            }
            Matcher::MaxType(max) => {
                let mut map = serializer.serialize_map(Some(2))?;
                map.serialize_entry("matches", "type")?;
                map.serialize_entry("max", &max)?;
                map.end()
            }
        }
    }
}

impl Hash for Matcher {
    fn hash<H: Hasher>(&self, state: &mut H) {
        match *self {
            Matcher::Equality => {
                state.write_u8(0);
            }
            Matcher::Regex(ref regex) => {
                state.write_u8(1);
                // This `as_str` is the only reason we can't `#[derive(Hash)]`.q
                regex.as_str().hash(state);
            }
            Matcher::Type => {
                state.write_u8(2);
            }
            Matcher::MinType(min) => {
                state.write_u8(3);
                min.hash(state);
            }
            Matcher::MaxType(max) => {
                state.write_u8(4);
                max.hash(state);
            }
        }
    }
}
```

</div></details>

This type can be parsed using `let matcher: Matcher = serde_json::from_value(&json)?;`, which is nice, and it can supply `Eq`, `Hash`, etc. Plus it reduces the amount of raw JSON munging throughout the crate.

Of course, like the other solutions, this would involve changing quite a bit of code in `pact_matching`, potentially on both the V2 and V3 branches. So I think this is worth discussing. I have some experimental code from last night which implements about 70% of this for V2 (pretty much everything except for changing the remaining tests), but I think we should talk about this before I go any further. :-)

**Comment by uglyog** [comment]
I think I'll start by back-porting the implementation from the v3-branch, because that has proper structures for matching rules. It will also make it easier to merge the changes into that branch.

**Comment by uglyog** [comment]
I have back ported the matching rules from the V3 branch. This has broken your consumer DSL. I will now fix this issue (should now be a trivial fix) and then update the consumer DSL to use the new matching rules.

**Comment by uglyog** [comment]
The side effect for porting the V3 matching rules is that it has fixed this issue.

**Comment by emk** [comment]
Great! In this case, once the tests pass, I think we're OK (at least as far as I know) to release 0.3 versions of pact_matching and pact_consumer, and that will make Rust Pact consumers much more powerful.

Let me know if you want help on the `pact_consumer` test updates. They should be mostly pretty easy.

My employer would love it if I wrote up a blog post about testing Rust applications with Pact on our company blog as soon as something is released.

**Comment by mefellows** [comment]
If you need any encouragement on that blog post... :)

**Comment by uglyog** [comment]
0.3.0 has been released to crates.io

**Comment by emk** [comment]
Yay! OK, I'll try to write a blog post early this coming week, assuming everything goes according to schedule at work. Thank you for working hard to get all my changes ready to release!
