### ISSUE TITLE
Cannot write multiple interactions to pact file when using plugins

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-reference#223]
I've noticed in my testing of the gRPC/Protobuf plugin, that only the last interaction that is tested can be written to the pact file, even if the `overwrite` flag on `pactffi_pact_handle_write_file` is set to `false`.

I'm not sure if this relates to plugins, the specific plugin or something else.

Attached is a log at TRACE level for a JS test that has several messages (both sync and async), however the problem is present even if I stick with just synchronous pacts.

[output.txt](https://github.com/pact-foundation/pact-reference/files/9815872/output.txt)

**Comment by rholshausen** [comment]
Is this running on OSX? Does it also occur on Linux?

**Comment by mefellows** [comment]
Yes OSX, I'll get a repro for you.

**Comment by mefellows** [comment]
🤦 

![Screen Shot 2022-11-04 at 2 21 28 pm](https://user-images.githubusercontent.com/53900/199878507-9ddf7c3b-5a9a-4e0e-a09b-4734d98a5710.png)
