### ISSUE TITLE
pact_matching: Should regular expression matchers always be anchored?

### ISSUE THREAD

**Issue by emk** [pact-foundation/pact-reference#23]
Below, we use `term!("^/users/[0-9]+$", "/users/12")` to specify the regular expression that we want to match.

But the pact documentation and unit tests seem to be inconsistent on this point. Are the `^` and `$` actually needed, in theory? If we omit them in Rust, then `bad1` and `bad2` would both match `pattern` below.

```rust
    let pattern = PactBuilder::new("C", "P")
        .interaction("I", |i| {
            // Unfortunatley, we appear to need a leading "^" and trailing "$"
            // on this regex, or else it will match the other examples below.
            i.request.path(term!("^/users/[0-9]+$", "/users/12"));
        })
        .build();
    let good = PactBuilder::new("C", "P")
        .interaction("I", |i| { i.request.path("/users/2"); })
        .build();
    let bad1 = PactBuilder::new("C", "P")
        .interaction("I", |i| { i.request.path("/users/2/posts"); })
        .build();
    let bad2 = PactBuilder::new("C", "P")
        .interaction("I", |i| { i.request.path("/account/1/users/2"); })
        .build();
    assert_requests_match!(good, pattern);
    assert_requests_do_not_match!(bad1, pattern);
    assert_requests_do_not_match!(bad2, pattern);
```

What's the correct behavior here? Is `pact_matching` interpreting `"regex"` correctly?

**Comment by bethesque** [comment]
My personal feeling is not to require the anchors, because it will break backwards compatibility.

**Comment by uglyog** [comment]
It should be up to the users to be strict or lax on the matching. Requiring the anchors will force stricter matching.
