### ISSUE TITLE
Protobuf 0.1.16 + Rust FFI Logger init causes test to fail

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-reference#230]
Noticed some odd behaviour.

Using Protobuf 0.1.16 + and invoking the Rust FFI Logger causes test to fail, as the plugin cannot start up.

- Test Run 1 - OK https://github.com/YOU54F/pact-ruby-ffi/actions/runs/3395789219
  - FFI v0.3.13
  - Protobuf 0.1.15
- Test Run 2 - Fail https://github.com/YOU54F/pact-ruby-ffi/actions/runs/3465598180
  - FFI v0.3.13
  - Protobuf 0.1.16
 - Test Run 3 - Fail https://github.com/YOU54F/pact-ruby-ffi/actions/runs/3465619746
  - FFI v0.3.14
  - Protobuf 0.1.16
 - Test Run 4 - (Removed `pactffi_logger_init`/`pactffi_logger_apply`) OK https://github.com/YOU54F/pact-ruby-ffi/actions/runs/3465602381
  - FFI v0.3.13
  - Protobuf 0.1.16
  - Test Run 5 - (Removed `pactffi_logger_init`/`pactffi_logger_apply`) OK https://github.com/YOU54F/pact-ruby-ffi/actions/runs/3465615651
  - FFI v0.3.14
  - Protobuf 0.1.16
  
  
gRPC tests appear to be failing whenever I invoke something like

```
      PactRubyFfi.pactffi_logger_init
      PactRubyFfi.pactffi_logger_attach_sink('stderr', PactRubyFfi::FfiLogLevelFilter['LOG_LEVEL_DEBUG'])
      PactRubyFfi.pactffi_logger_apply
      PactRubyFfi.pactffi_log_message('pact_ruby', 'INFO', 'pact ruby grpc is alive') 
```

only noticed the failure today, as my CI run, is installing the latest proto plugin, and only got a passing test again, when I set the log level filter to 0. The current value is mapping through as `4` to the underlying ffi

edit: _sidenote_ wasn't sure on the best repo, pact_plugins, pact proto or this one, so just popped it here for now

**Comment by rholshausen** [comment]
Looks like it is getting IO errors trying to connect to the plugin. I don't think this is related to logging, as I can see some logs from the plugin, or maybe, the amount of logging is exhausting some buffer and causing the IO errors.

The plugin creates a log file in the plugin directory, it might be worth while attaching those files as build artifacts so we can see if there is any error from the plugin side

**Comment by YOU54F** [comment]
Will close this for now and re-raise if I see the issue crops up again in a new release
