### ISSUE TITLE
pactffi_verifier_add_directory_source does not filter files based on provider name

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-reference#233]
**Issue:** 

pactffi_verifier_add_directory_source does not filter files based on provider name. 

**Expected:** 

If using pactffi_verifier_add_directory_source, based on the documentation 

> Adds a Pact directory as a source to verify. All pacts from the directory that match the
> provider name will be verified.

1. Does this mean any pact files with the name that matchers the provider name in `pactffi_verifier_set_provider_info`
2. Does this mean any json files, that contain a `provider.name` value that matches that set in `pactffi_verifier_set_provider_info`

I think I would expect

- Combination of 1 & 2. Check for pact files matching the name, then introspect into the pact to check for matching `provider.name`
- 2. Check any json file in the directory, and check for `provider.name`. A user could have a pact file they have shared manually and renamed the file, but not modified the contents.

**Actual:**

1. `pactffi_verifier_set_provider_info` has a name of a provider that does not exist
2. No `pactffi_verifier_set_consumer_filters` are applied
3. `pactffi_verifier_add_directory_source` selects all pacts for verification 

![Screenshot 2022-12-06 at 14 31 51](https://user-images.githubusercontent.com/19932401/205939522-a9653969-76b1-44f5-8070-f5263d86bbf5.png)

**Comment by rholshausen** [comment]
It is meant to use the provider name from within the Pact file (`provider.name`), not the filename.
