### ISSUE TITLE
RUST implementation of mock server list retruns error status

### ISSUE THREAD

**Issue by AssafKatz3** [pact-foundation/pact-reference#24]
For some reason the status of each of mocks in pact_mock_server_cli defines by matchers check and therefore it almost always error. I changed it in [my fork](https://github.com/AssafKatz3/pact-reference) to always ok, but I am not sure that it is good idea. Anway, as I see it, the status should report the status of mock server, and therefore should be ok unless the mock server itself has some error.

**Comment by uglyog** [comment]
The status is not of the mock server, but the verification state. The status will be an error if the mock server has received any requests that were not matched correctly.

**Comment by AssafKatz3** [comment]
I agree, but currently it is error even if no request was sent and even valid one (I used the example) was sent.

**Comment by uglyog** [comment]
It is behaving as designed. The status will be an error until the mock server receives all the requests it is expecting. Here is an example use:

```console
$ ./target/debug/pact_mock_server_cli list
Mock Server Id                    Port   Provider  Status
$ ./target/debug/pact_mock_server_cli create -f pact_matching/tests/pact.json
14:56:48 [INFO] Creating mock server from file pact_matching/tests/pact.json
14:56:48 [WARN] No metadata found in pact file "\"pact_matching/tests/pact.json\"", assuming V2 specification
Mock server "e9cc64e0322f416788139ec4251edb22" started on port 9000
$ ./target/debug/pact_mock_server_cli create -f pact_matching/tests/test_pact.json
14:56:57 [INFO] Creating mock server from file pact_matching/tests/test_pact.json
Mock server "919670551bc4426b993e799faf3595cd" started on port 9001
$ ./target/debug/pact_mock_server_cli list
Mock Server Id                    Port   Provider         Status
"919670551bc4426b993e799faf3595cd"  9001  "test_provider"  "error"
"e9cc64e0322f416788139ec4251edb22"  9000  "Alice Service"  "error"
$ curl 'http://localhost:9000/mallory?name=ron&status=good'
"That is some good Mallory."
$ 
$ ./target/debug/pact_mock_server_cli list
Mock Server Id                    Port   Provider         Status
"919670551bc4426b993e799faf3595cd"  9001  "test_provider"  "error"
"e9cc64e0322f416788139ec4251edb22"  9000  "Alice Service"  "ok"
```

Once the first mock server got the correct request (via curl), it's status changed to ok.

**Comment by uglyog** [comment]
I might change the heading to "Verification State" to avoid confusion.
