### ISSUE TITLE
pact_verifier_cli: min max matchers do not seem to work

### ISSUE THREAD

**Issue by livinglogic-nl** [pact-foundation/pact-reference#240]
I'm using pact_verifier_cli  0.9.19 with a version 3 PACT file.
I have matching rules as the following:
```json
"matchingRules": {
  "body": {
    "$": {
      "matchers": [
        {
          "match": "type"
        },
        {
          "min": "0"
        },
        {
          "max": "0"
        }
      ]
    }
  }
}
```

When verifying this and the response has an array of multiple items, it still gets verified. Is this expected behaviour?

**Comment by mefellows** [comment]
You can't specify an array that has a minimum of 0 and maximum of 0. See https://docs.pact.io/faq#why-is-there-no-support-for-specifying-optional-attributes and #optional.
