### ISSUE TITLE
fn matcher_from_integration_json in mockserver/bodies.rs doesn't support all MatchingRules

### ISSUE THREAD

**Issue by orj** [pact-foundation/pact-reference#247]
`fn matcher_from_integration_json` in `mockserver/bodies.rs` doesn't support all `MatchingRule` types.

v4 Matching rules like `server`, `boolean`, statusCode` etc are not supported using the format described in https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi/IntegrationJson.md.

Also, the documentation says `pact:matcher:type` for date/time values should be `datetime` but the code uses `timestamp`.

**Comment by rholshausen** [comment]
Just a note that `matcher_from_integration_json` is marked as deprecated and should be replaced with `MatchingRule::create`.

**Comment by rholshausen** [comment]
`matcher_from_integration_json` has now been refactored and supports all matching rules
