### ISSUE TITLE
Add support for JUnit output in verifier

### ISSUE THREAD

**Issue by gregtyler** [pact-foundation/pact-reference#257]
_[Original Slack thread](https://pact-foundation.slack.com/archives/C5F4KFKR8/p1676278643972909)_

The [old Ruby verifier](https://github.com/pact-foundation/pact-provider-verifier) supported an option to format the output as JUnit XML (`--format=RspecJunitFormatter`), which is very helpful when running Pact as part of a larger pipeline since it allows us comb failures from all tests.

It would be great if the new verifier could support JUnit output too.

(NB: there's [an existing issue in the Ruby verifier](https://github.com/pact-foundation/pact-provider-verifier/issues/94) about overwriting output when testing against multiple consumers)

**Comment by rholshausen** [comment]
0.10.3 has been released with a JUnit XML output option
