### ISSUE TITLE
Header is parsed incorrectly

### ISSUE THREAD

**Issue by sergeyklay** [pact-foundation/pact-reference#259]
Hi,

I seem to have hit a dead end with the header verification.  Relevant part of pact looks as follows:

```jsonc
"response": {

        // ...

        "headers": {
          "Last-Modified": "Sun, 12 Mar 2023 01:21:35 GMT"
        },

        // ...

       "matchingRules": {
          "$.headers.Last-Modified": {
            "match": "regex",
            "regex": "^[A-Za-z]{3},\\s\\d{2}\\s[A-Za-z]{3}\\s\\d{4}\\s\\d{2}:\\d{2}:\\d{2}\\sGMT$"
          },

          // ...

        }

      }

  // ...

  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
```

I think the regular expression in Python consumer is correct, since I have tested it many times using various tools:

```python
# The date and time format used in the Last-Modified header according to
# RFC 7231 is described in section 7.1.1.1.
#
# Examples:
#
#    Last-Modified: Mon, 12 Feb 1996 11:36:28 GMT
#    Last-Modified: Sat, 11 Mar 2023 21:56:41 GMT
#
LAST_MODIFIED_REGEX = r'^[A-Za-z]{3},\s\d{2}\s[A-Za-z]{3}\s\d{4}\s\d{2}:\d{2}:\d{2}\sGMT$' 
```

But when I try to verify it, it somehow compares for an exact match, without using a regular expression:

```
Pending Failures:

1) Verifying a pact between ProductServiceClient and ProductService Given there is a product with ID 1 - a request for a product
    1.1) includes header 'Last-Modified' with value 'Sun'
           Expected header 'Last-Modified' to have value 'Sun' but was 'Sun'
           Expected header 'Last-Modified' to have value '12 Mar 2023 01:21:35 GMT' but was '12 Mar 2023 01:21:52 GMT'
```

![image](https://user-images.githubusercontent.com/1256298/224532416-33c7376c-909b-4358-9da0-28e74adb6f54.png)

The difference in seconds: 35 vs 52.  And it fails because (I guess. I could be wrong.) in pact I have:
- “Sun, 12 Mar 2023 01:21:**35** GMT”

but providers returns
- “Sun, 12 Mar 2023 01:21:**52** GMT”

I use the same approach ( using regular expression test) for other headers like ETag, Content-Type and they are fine, verification passes as expected. The problem is only with this header.

Of course, I can create the required date on the provider side using request to `/_pact/provider_states`. However, in this case all my efforts will be to provide an exact match, and I would like to use the pattern here.

In one of the chats, @TimothyJones suggested that this is the bug with the header parsing where it’s splitting on **`,`**. Looks like a bug in pact-reference, probably. Anyway, there is a similar issue: https://github.com/pact-foundation/pact-js/issues/1058

---

Versions:

**Verifier**
```
% pact_verifier_cli --version
pact verifier version   : v0.10.3
pact specification      : v4.0
models version          : v1.0.4
```

**Broker**

```
Docker images: pactfoundation/pact-broker:latest
```

**Comment by rholshausen** [comment]
pact_verifier_cli 0.10.4 has been released with a fix for this

**Comment by sergeyklay** [comment]
I can confirm it, now everything works as expected. Thanks for the quick fix!
