### ISSUE TITLE
There seems to be no way to shut down the master server?

### ISSUE THREAD

**Issue by ratkins** [pact-foundation/pact-reference#26]
We're attempting to run `pact_mock_server_cli` from pre- and post-action scripts in an Xcode scheme.

There seems to be no way to stop the master server and all its sub-servers (for our post-action script.) Are we missing something?

**Comment by uglyog** [comment]
You can shut it down by killing the process, but I'll add a shutdown master command.

**Comment by uglyog** [comment]
I've added a `shutdown-master` which will force the server process to terminate.

**Comment by mefellows** [comment]
This is done now.
