### ISSUE TITLE
String Provider State Params Serialised As Numbers

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-reference#263]
See: https://github.com/pact-foundation/pact-net/issues/449

If a provider state param just happens to contain only numbers then it's serialised to the pact file as a number instead of a string.

You'd expect the pact file to contain:

```json
"providerStates": [
  {
    "name": "state with param",
    "params": {
      "issue": "449" // <-- note that this is a string
    }
  }
]
```

but it contains 

```json
"providerStates": [
  {
    "name": "state with param",
    "params": {
      "issue": 449 // <-- note that this is a number instead of a string
    }
  }
]
```

**Comment by rholshausen** [comment]
If you are using the function `pactffi_given_with_param` you need to pass through the value in JSON form. If it is a string value, it must be wrapped in double quotes, i.e. 

```c
pactffi_given_with_param(interaction, "state with param", name: "issue", value: "\"449\"")
```

**Comment by rholshausen** [comment]
> What happens if a regular string has quotes around it?

If it can't parse it as JSON, it falls back to using the raw string. The problem here is it can parse it as JSON, which is needed in case you actually want to pass numbers and booleans in.

**Comment by rholshausen** [comment]
This is not meant to be the format the user provides, that should be an idiomatic  value for the language being used. For instance, with Ruby, Python or Groovy the user would be able to pass a map of values, and it should be converted to JSON behind the scenes.

**Comment by YOU54F** [comment]
> I'd question if this is really closed as completed. I think it's clear that users could get really weird unexpected behaviour with this.

It would be best to prove or disprove this with tests, and then we have something to work with, as well as some documentation for users.

As to Ron's commit to the docstring [here](https://github.com/pact-foundation/pact-reference/issues/263#issuecomment-1510555100)


I've implemented that in your issue repro over in pact-net (thank you!), and using the documented suggestion by Ron (parsing as json) works as per your test case. 

[delta](https://github.com/pact-foundation/pact-net/compare/fix/numeric-provider-state-param...YOU54F:pact-net:fix/numeric-provider-state-param?expand=1)
[passing action run](https://github.com/YOU54F/pact-net/actions/runs/9260857979)

Edge cases are to be expected but happy to unearth them.
