### ISSUE TITLE
release of pact_mock_server_cli

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-reference#289]
Hey @uglyog 

Can we put out a release of pact_mock_server_cli

I'd like to get native aarch64 support out for macos from this commit

[a7349c74](https://github.com/pact-foundation/pact-reference/pull/266) - feat: pact_mock_server_cli aarch64 osx (Yousaf Nabi, Wed Apr 12 12:29:14 2023 +0100)

I was going to give it a go via the `release.groovy` script however I am not sure if it needs to have a major bump due to the breaking change notice on pact_models

sooo just safer to let you make the release call.

danke muchly

**Comment by rholshausen** [comment]
On it!

**Comment by rholshausen** [comment]
It's not a breaking change for the CLI, as it still has the same interface.
