### ISSUE TITLE
Include interaction description in verification results

### ISSUE THREAD

**Issue by gregtyler** [pact-foundation/pact-reference#292]
The verification results published from the Rust verifier are extremely streamlined, containing only the interaction ID, success boolean and any mismatches. This is easier to parse than the old verification results, which contained a myriad of data even if the test was successful.

However, interaction IDs are not an easy way of understanding which test failed, as they must then be cross-referenced with a separate document to track them back to the test in code.

To make this easier, could you add the interaction description to the verification results too? This would make it much easier to get a quick understanding of what's broken from the results themselves.

**Comment by rholshausen** [comment]
The verification results format is defined by the Pact broker project. I think it will just ignore additional fields, but I am waiting on conformation of that.

**Comment by JP-Ellis** [comment]
Closing this as @rholshausen appears to have implemented the issue and the internal ticket has been marked is _done_ :)
