### ISSUE TITLE
Add support for `statusCode` matcher in FFI

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-reference#296]
Currently the FFI only supports an exact match: https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_ffi/src/mock_server/handles.rs#L1196

**Comment by rholshausen** [comment]
Support exists using [pactffi_response_status_v2](https://docs.rs/pact_ffi/latest/pact_ffi/mock_server/handles/fn.pactffi_response_status_v2.html)

**Comment by mefellows** [comment]
Awesome, thanks.
