### ISSUE TITLE
FFI calls > Support generators for async message

### ISSUE THREAD

**Issue by tienvx** [pact-foundation/pact-reference#338]
These scenarios in compatibility suite indicate that generators are supported for async message on consumer side:

- [Supports the use of generators with the message body](https://github.com/pact-foundation/pact-compatibility-suite/blob/main/features/V3/message_consumer.feature#L63-L69)
- [Supports the use of generators with message metadata](https://github.com/pact-foundation/pact-compatibility-suite/blob/main/features/V3/message_consumer.feature#L71C13-L78)

But currently I think generators are not working when using this `pactffi_message_reify` FFI call.

**Comment by mefellows** [comment]
Reify doesn't support synchronous messages and a bunch of things. I think you're best using the message-related iterators to extract these values. The method should probably be marked as deprecated.

**Comment by tienvx** [comment]
I don't know how to use those iterators methods yet. I can't find any example code. Look like there are no language using those methods yet?

btw thanks for the suggestion.

**Comment by mefellows** [comment]
No worries!

Btw I use it in Go here: https://github.com/pact-foundation/pact-go/blob/master/internal/native/message_server.go#L397-L519.

**Comment by tienvx** [comment]
I'm able to use those iterator methods, but there 2 small problems:
* The code is too long for me (15 lines of code vs 1 when using `pactffi_message_reify`)
* An annoying issue related to panic #344

I also updated `pactffi_message_reify` with this PR #342, so for now I will continue using it.

**Comment by tienvx** [comment]
Closed as implemented

**Comment by mefellows** [comment]
Nice one! I'm interested - does this work on synchronous messages also (both the request and/or response side)?

**Comment by tienvx** [comment]
I didn't touch on synchronous message FFI calls. But I have a quick look at `synchronous_messages_iter` and I think it is already implemented:
* https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_consumer/src/builders/message_iter.rs#L56
* https://github.com/pact-foundation/pact-reference/blob/master/rust/pact_consumer/src/builders/message_iter.rs#L76

Currently I can't implement synchronous message in compatibility suite in PHP so I can't test it.

**Comment by mefellows** [comment]
oh yes, I know they support generators. I guess I was asking if you could use `pactffi_message_reify` on a sync message. I can look at code, I was being lazy :P

**Comment by tienvx** [comment]
> if you could use pactffi_message_reify on a sync message

No, I don't think so.
