### ISSUE TITLE
'Access-Control-Allow-Origin' header is duplicated in the latest build available via docker v0.1.0

### ISSUE THREAD

**Issue by Byron-TW** [pact-foundation/pact-reference#36]
When running the stub server v0.1.0, and querying the OPTIONS as is done by browsers using the `fetch` API, the returned header contains the `Allow-Control-Access-Origin` twice. This is an error, as indicated by this message generated by Chrome.

```
Failed to load http://localhost:3001/<redacted>: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://localhost:3000' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
The response looks like this:

![invalid-allow-access-control](https://user-images.githubusercontent.com/15169434/45024787-14e5db00-b03a-11e8-88e3-a63ad59748a3.png)

### Suggestions

Maybe dependencies were silently updated when rebuilding the pact server, as a `Cargo.lock` file is absent. The bug might have been introduced transitively.

### How to reproduce

This is only a partial reproduction, but at least gives you the correct image to play with locally.

```
# assuming a pact is placed into `./pacts`
docker run -v $PWD/pacts:/pacts  -p 8081:8081 pactfoundation/pact-stub-server:v0.1.0 -p 8081 -d /pacts
``

When running a GET with the browsers `fetch` API, you will see the issue above.

**Comment by uglyog** [comment]
This is an error with the stub server, related to https://github.com/uglyog/pact-stub-server/issues/14. I'll move it there.

**Comment by uglyog** [comment]
Moved to https://github.com/uglyog/pact-stub-server/issues/15
