### ISSUE TITLE
HTTPS pact broker not supported

### ISSUE THREAD

**Issue by audunhalland** [pact-foundation/pact-reference#37]
Running the verifier with:

`./target/debug/pact_verifier_cli --provider-name myProvider --broker-url https://anything.com --hostname http://localhost:9999 --state-change-url http://localhost:9999/_pactSetup`

Yields:

```
Failures:

0) Failed to load pact - Could not load pacts from the pact broker 'https://anything.com' - IoError("Failed to access pact broker path \'/\' - \"Invalid scheme for Http\". URL: \'https://anything.com\'")
```

I guess this is related to https://github.com/hyperium/hyper/issues/1009, and https support needs to be provided as a separate library.

I would be more than happy to help the project, so maybe you'll see a PR from me when I get the time.

**Comment by audunhalland** [comment]
Awaiting a response from maintainer, as I'm not sure how to proceed; whether to go for a more high level client like e.g. reqwest instead of hyper.

**Comment by uglyog** [comment]
If reqwest works, we can go with that. There were no other options when this project was started than hyper. It is also still using the older blocking version, so an upgrade of hyper would require a rewrite.

**Comment by audunhalland** [comment]
Ok, I can try first to upgrade to async hyper, and see what needs to be changed first. Not yet familiar with the code base and what will be implicated, but I'll surely find out.

**Comment by uglyog** [comment]
Have a look at https://github.com/uglyog/pact-stub-server, I went through the upgrade there.

**Comment by audunhalland** [comment]
Thanks, but just out of curiosity, what's the relation between that project and this project's pact_mock_server(_cli)?

**Comment by uglyog** [comment]
The stub server uses the pact-rust matching libraries, but is just a convenience for people who want to have a server running off a set of pact files. The matching is a lot looser than the pact_mock_server.

**Comment by uglyog** [comment]
Now that you have done all the hard work, we can come back to this issue. We can now use hyper-tls and native-tls crates to support HTTPS.

**Comment by audunhalland** [comment]
Up to you to decide how you want it to work. `reqwest` is a more high level client and will support stuff like redirect and proxies. Don't know if it's needed. I don't have a very strong opinion either, although `hyper` doc recommends that if you just want "a http client" (which we do?), use `reqwest`.
