### ISSUE TITLE
When use .id method for PactDslJsonBody, it is giving 500 error when request the pact json 

### ISSUE THREAD

**Issue by chetanjadav77** [pact-foundation/pact-reference#39]
Hi i have this body in consumer tests
```
PactDslJsonBody` response = new PactDslJsonBody()
                //.numberType("id")
                //.id("id")
                .id()
                //.numberValue("id", 1)
                .stringType("clientId")
                .stringType("clientSecret")
                .stringValue("applicationName","flex-publish-service")
                .stringValue("description","abc")
```
after creating json it is giving 500 errors for post call, i am facing problem with id. if i use .id("id",10L) it worked but i want id to be random and will be ignored in provider verification

Here is the error when i hit http://localhost:18101/api/authentication/applications POST call with 
```
{
  "applicationName": "flex-publish-service",
  "description": "abc"
}

```
```
comparing to expected request: Request { method: "POST", path: "/api/authentication/applications", query: None, headers: Some({"X-App-Registration-Key": "Ld61vMw2jKLBNClekKCkSSshETpX0pUl4S0YpJwPvWBpO4sB", "Content-Type": "application/json"}), body: Present([123, 34, 97, 112, 112, 108, 105, 99, 97, 116, 105, 111, 110, 78, 97, 109, 101, 34, 58, 34, 102, 108, 101, 120, 45, 112, 117, 98, 108, 105, 115, 104, 45, 115, 101, 114, 118, 105, 99, 101, 34, 44, 34, 100, 101, 115, 99, 114, 105, 112, 116, 105, 111, 110, 34, 58, 34, 115, 116, 114, 105, 110, 103, 34, 125]), matching_rules: MatchingRules { rules: {"body": Category { name: "body", rules: {"$.description": RuleList { rules: [Type], rule_logic: And }} }} }, generators: Generators { categories: {BODY: {"$.description": RandomString(20)}} } }
token = Root
body_cursor = Object({"applicationName": String("flex-publish-service"), "clientId": String("string"), "clientSecret": String("string"), "description": String("abc"), "id": Number(1234567890)})
token = Field("id")
body_cursor = Object({"applicationName": String("abc"), "clientId": String("string"), "clientSecret": String("string"), "description": String("abc"), "id": Number(1234567890)})
thread '<unnamed>' panicked at 'Rng.gen_range called with low >= high', /home/ronald/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.2/src/lib.rs:519:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by chetanjadav77** [comment]
{
    "provider": {
        "name": "service"
    },
    "consumer": {
        "name": "abc-service"
    },
    "interactions": [
        {
            "description": "Registers an application",
            "request": {
                "method": "POST",
                "path": "/api/authentication/applications",
                "headers": {
                    "X-App-Registration-Key": "Ld61vMw2jKLBNClekKCkSSshETpX0pUl4S0YpJwPvWBpO4sB",
                    "Content-Type": "application/json"
                },
                "body": {
                    "description": "string",
                    "applicationName": "fservice"
                },
                "matchingRules": {
                    "body": {
                        "$.description": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        }
                    }
                },
                "generators": {
                    "body": {
                        "$.description": {
                            "type": "RandomString",
                            "size": 20
                        }
                    }
                }
            },
            "response": {
                "status": 200,
                "headers": {
                    "Content-Type": "application/json; charset=UTF-8"
                },
                "body": {
                    "clientId": "string",
                    "description": "abc",
                    "clientSecret": "string",
                    "id": 1234567890,
                    "applicationName": "fservice"
                },
                "matchingRules": {
                    "body": {
                        "$.id": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$.clientId": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        },
                        "$.clientSecret": {
                            "matchers": [
                                {
                                    "match": "type"
                                }
                            ],
                            "combine": "AND"
                        }
                    },
                    "header": {
                        "Content-Type": {
                            "matchers": [
                                {
                                    "match": "regex",
                                    "regex": "application/json;\\s?charset=(utf|UTF)-8"
                                }
                            ],
                            "combine": "AND"
                        }
                    }
                },
                "generators": {
                    "body": {
                        "$.id": {
                            "type": "RandomInt",
                            "min": 0,
                            "max": 2147483647
                        },
                        "$.clientId": {
                            "type": "RandomString",
                            "size": 20
                        },
                        "$.clientSecret": {
                            "type": "RandomString",
                            "size": 20
                        }
                    }
                }
            },
            "providerStates": [
                {
                    "name": "There is a request to register an application"
                }
            ]
        }
    ],
    "metadata": {
        "pactSpecification": {
            "version": "3.0.0"
        },
        "pact-jvm": {
            "version": "3.5.21"
        }
    }
}

**Comment by uglyog** [comment]
This has been fixed and I've also updated the pact-stub-server to 0.3.0.
