### ISSUE TITLE
Create multi-arch images for pactfoundation/pact-ref-verifier

### ISSUE THREAD

**Issue by spockz** [pact-foundation/pact-reference#397]
There are aarch64/arm64 builds available of the cli, see#160 #320. However, the docker image is only available in the AMD64 flavour: https://hub.docker.com/r/pactfoundation/pact-ref-verifier/tags. The previous Ruby flavour image is available in multiple architectures.

Can we please also create the image for arm64?

**Comment by rholshausen** [comment]
Latest docker image is now multi architecture.

**Comment by spockz** [comment]
Thank you, much obliged.
