### ISSUE TITLE
docs: note musl based static builds, that work across linux distros + alpine ffi static & shared libs

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-reference#416]
it would be good to document this on the readme, so users are aware that

- Alpine is now supported
- The builds are static, and therefore the single binary works across musl or glibc based distros (excluding ffi)
- pact_ffi library comes in both static `*.a` & shared `*.so` variants for musl, depending on the consuming client libraries requirements for ffi interop

| library | alpine support | version | 
| -- | -- | -- | 
| pact_ffi | ✅  | - `x86_64` `.a` from [0.2.4](https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.2.4)
| | | - `aarch64` `.a` from [0.4.15](https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.4.15)|
| | | - `.so` from [0.4.17](https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.4.17) | |
| pact_mock_server_cli | ✅ | - [1.0.5](https://github.com/pact-foundation/pact-reference/releases/tag/pact_mock_server_cli-v1.0.5)
| pact_verifier_cli | ✅ | - [1.1.1](https://github.com/pact-foundation/pact-reference/releases/tag/pact_verifier_cli-v1.1.1)
| pact-stub-server | ✅ | - [0.6.0](https://github.com/pact-foundation/pact-stub-server/releases/tag/v0.6.0) | 
| pact-plugin-cli | ✅ | - [0.1.2](https://github.com/pact-foundation/pact-plugins/releases/tag/pact-plugin-cli-v0.1.2) | 
| pact-protobuf-plugin | ✅ | - [0.3.15](https://github.com/pactflow/pact-protobuf-plugin/releases/tag/v-0.3.15) | 
| pact-csv-plugin | ✅ | - [0.0.6](https://github.com/pact-foundation/pact-plugins/releases/tag/csv-plugin-0.0.6) |

**Comment by mefellows** [comment]
Nice! We should update here also: https://docs.pact.io/docker

**Comment by YOU54F** [comment]
So we have an issue with the pact_ffi shared library, for aarch64-musl `.so` in `0.4.20`

- [0.4.19 passing](https://github.com/YOU54F/pact-ruby-ffi/actions/runs/9087464050) when integrated with ruby (loads the `.so` file)
- [0.4.20 failing](https://github.com/YOU54F/pact-ruby-ffi/actions/runs/9087466381)

Error

```
LoadError:
  Could not open library '/app/lib/pact/../../ffi/linux-arm64-musl/libpact_ffi.so': Error relocating /app/lib/pact/../../ffi/linux-arm64-musl/libpact_ffi.so: __builtin_copysignq: symbol not found.
  Searched in <system library path>, /usr/lib, /usr/local/lib, /opt/local/lib
# /usr/local/bundle/gems/ffi-1.16.3/lib/ffi/dynamic_library.rb:65:in `load_library'
```

Seems to be exclusive to aarch64, and the dynamic library only. amd64 tests are passing in pact-php as well using the shared library, and the static .a is being used and tested successfully in pact-js-core in this [PR](https://github.com/pact-foundation/pact-js-core/pull/507)

First reported by @tienvx over in pact-php alpine [PR](https://github.com/pact-foundation/pact-php/pull/613#discussion_r1599747130) - Thanks Tien!

**Comment by YOU54F** [comment]
So I've just built the aarch64 musl libs locally on my macbook, 

https://github.com/pact-foundation/pact-reference/blob/e44458a8616856d3726470dd8f3884340999bf1e/rust/pact_ffi/release-linux.sh#L82-L111

Copied these over to pact-php

```
cp ../release_artifacts/libpact_ffi-linux-aarch64-musl.so ~/dev/pact-foundation/pact-php/bin/pact-ffi-lib/pact.so
```

Green php tests.

<img width="1449" alt="Screenshot 2024-05-15 at 18 44 43" src="https://github.com/pact-foundation/pact-reference/assets/19932401/85c3e504-3c14-47bd-abb7-8a827b106d69">

note have tried regenerating the `.so` from the released 0.4.20 `.a` but get the same missing symbol issue, so not sure what has caused it

**Comment by YOU54F** [comment]
I think this was due to stripping of the symbols from the static archive, prior to generating the shared object file. It's possible to force the generation of the *.so at compile time with some rust flags, so that has been performed along with a smoke test to ensure its loading correctly in #432

**Comment by YOU54F** [comment]
> Nice! We should update here also: https://docs.pact.io/docker

Updated PR for docs page here

https://github.com/pact-foundation/docs.pact.io/pull/345
