### ISSUE TITLE
Verifier CLI: README suggests only Pact V3 is supported, but in practice V1-V4 is supported.

### ISSUE THREAD

**Issue by mjpieters** [pact-foundation/pact-reference#423]
The Verifier CLI readme is confusing about what Pact specifications it supports. In practice, all versions are supported but the README suggests only V3 is covered.

The Verifier CLI README [starts with](https://github.com/pact-foundation/pact-reference/blob/e44458a8616856d3726470dd8f3884340999bf1e/rust/pact_verifier_cli/README.md#L3):

> It implements the [V3 Pact specification](https://github.com/pact-foundation/pact-specification/tree/version-3).

but [further down the page](https://github.com/pact-foundation/pact-reference/blob/e44458a8616856d3726470dd8f3884340999bf1e/rust/pact_verifier_cli/README.md#L340) there is a section referencing V4:

> ## Verifying V4 Pact files that require plugins

Given that the CLI is built using the [`rust_verifier` library](https://github.com/pact-foundation/pact-reference/tree/e44458a8616856d3726470dd8f3884340999bf1e/rust/pact_verifier), which explicitly states it implements V3 and V4, the README is clearly out of date.

Moreover, the tool accepts older specification formats too, because the [`pact_models` library](https://github.com/pact-foundation/pact-reference/blob/e44458a8616856d3726470dd8f3884340999bf1e/rust/pact_models/) converts these to V3 contracts anyway. So in practice, you can use it to verify contracts using any Pact schema version, from V1 through to V4.

Please update the README to reflect this.

**Comment by rholshausen** [comment]
README has been updated
