### ISSUE TITLE
Regex matching for full text bodies is missing

### ISSUE THREAD

**Issue by coertmetz** [pact-foundation/pact-reference#43]
Regex matching for full text bodies would be nice to have.

E.g. something like this would be expected to work:

    "request": {
        "body": "some full text body",
        "matchingRules": {
            "body": {
                "$": {
                    "matchers": [
                        {
                            "match": "regex",
                            "regex": "some regex"
                        }
                    ]
                }
            }
        }
     }

or maybe this makes sense:

    "request": {
        "body": "some full text body",
        "matchingRules": {
            "body": {
                "matchers": [
                    {
                        "match": "regex",
                        "regex": "some regex"
                    }
                ]
            }
        }
    }

**Comment by uglyog** [comment]
It's the first example, because the matching on bodies requires a path.

**Comment by uglyog** [comment]
Version 0.5.2 has been released of the pact_matching crate with this fix
