### ISSUE TITLE
Verifier cannot parse iso8601Date RegEx from pact-js

### ISSUE THREAD

**Issue by audunhalland** [pact-foundation/pact-reference#46]
Pact generated by js library `@pact-foundation/pact/dsl/matchers` using the `iso8601Date` matcher generates a regular expression that cannot be parsed in Rust:

```
1) Verifying a pact between A and B Given C - D returns a response which has a matching body
    $.somePath -> '^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))?)$' is not a valid regular expression - regex parse error:
    ^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))?)$
```

Ref https://github.com/rust-lang/regex/issues/127#issuecomment-154713666

**Comment by audunhalland** [comment]
Solution suggested by regex author: https://www.reddit.com/r/rust/comments/b4yb7c/do_rust_regular_expressions_support_recursion/ej9ypsx/

**Comment by uglyog** [comment]
I'm not going to support that regex. In fact, I'm going to have a serious talk to whoever wrote that. And I think I know who it was :-D

**Comment by audunhalland** [comment]
Is this even a bug in `pact-reference` given that you think that the regex should never have been generated in the first place?

Instead move the bug to https://github.com/pact-foundation/pact-js? When that library uses pact-reference it will get fixed.

**Comment by uglyog** [comment]
No, I'll switch to using the Oniguruma lib because that is based on Ruby regex. That will hopefully fix the issue for you.

But going forward I'm working on changing Pact-JS to use the Rust libraries, which have support for date and time matching.

**Comment by uglyog** [comment]
0.6.1 is released

**Comment by audunhalland** [comment]
I haven't had the chance to verify this yet, because when I discovered the bug I did a quick fix and rewrote the consumer pact to match string instead of date. I'll come back and verify this fix when I find the time.
