### ISSUE TITLE
Using pactffi_with_pact_metadata with duplicate namespace, overwrites existing namespace contents

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-reference#466]
Writing a pact with the following metadata

```
      pactffi_with_pact_metadata(pact, 'namespace1', 'var_1', 'value_1')
      pactffi_with_pact_metadata(pact, 'namespace1', 'var_2', 'value_2')
      pactffi_with_pact_metadata(pact, 'namespace2', 'var_1', 'value_1')
      pactffi_with_pact_metadata(pact, 'namespace2', 'var_2', 'value_2')
      pactffi_with_pact_metadata(pact, 'pactRust', 'var_1', 'var_1')
      pactffi_with_pact_metadata(pact, 'pactRust', 'var_2', 'var_2')
```

Results in the following metadata.

```json
  "metadata": {
    "namespace1": {
      "var_2": "value_2"
    },
    "namespace2": {
      "var_2": "value_2"
    },
    "pactRust": {
      "mockserver": "1.2.9",
      "models": "1.2.3",
      "var_2": "var_2"
    },
    "pactSpecification": {
      "version": "3.0.0"
    }
```

1. `namespace1` only has the last entry `{"var_2": "value_2"}`, missing  `{"var_1": "value_1"}`
1. `namespace2` only has the last entry `{"var_2": "value_2"}`, missing  `{"var_1": "value_1"}`
1. `pactRust` only has the last entry `{"var_2": "value_2"}`, missing  `{"var_1": "value_1"}`, existing `pactRust` entries not removed. (`models` /`mockserver`)

Other notes.

- `pactSpecification` namespace appears to be protected and cannot write to it
- `pactRust` library versions are not overwritten, so only newly added keys bar the latest are removed, in a single pact execution

Source location for function

https://github.com/pact-foundation/pact-reference/blob/f5ddf3d353149ae0fb539a1616eeb8544509fdfc/rust/pact_ffi/src/mock_server/handles.rs#L1140-L1152

Should we do the following

1. Fix so all added metadata is retained, unless a duplicate call is made which overwrites an existing namespace & key
2. Create a v2 suffixed function that can accept json, rather than a using having to make multiple calls. This pattern is used in the message metadata v2 functions, but I believe this was mainly done to accept matching rules in the integration json format but are not relevant for generic top level Pact file metadata

**Comment by JP-Ellis** [comment]
I do think the current functions needs to be fixed. Adding to entries to a namespace _should_ result in these two entries being in the namespace. This is a bug which I highly doubt anyone is relying on.

Now for accepting JSON, this really should be added. It can also fallack to handling the string as-is, namely:

1. Try and deserialise the `value` into a `serde_json::Value`:
   2. If that succeeds, proceed with the given value in the code as before
   3. If that fails, proceed with the original string as the value

This would be a breaking change to the current behaviour for strings which were handled as strings, but can be deserialized into a JSON value:

| Input Str/Current | Fixed |
|------- | ----- |
| `"null"` | `null` |
| `"1"` | `1` |
| `r#"{"foo": "bar"}#` | `{"foo": "bar"}` |

Given this function is only for Pact metadata, I do wonder whether incorporating a breaking change into the current function is justified? Or we just be safe and create a `_v2` function?

**Comment by YOU54F** [comment]
Cheers Ron!
