### ISSUE TITLE
pact_verifier_cli process exits with status code 0 even if verification has failed

### ISSUE THREAD

**Issue by audunhalland** [pact-foundation/pact-reference#47]
Integrating pact_verifier_cli into our CI pipeline revealed that that build does not fail when pact verification fails. We need the pact_verifier_cli process to return a non-zero status code when there are errors with pact verification.

**Comment by uglyog** [comment]
It should be exiting with a status of 2. I'll double check what is going on.

**Comment by uglyog** [comment]
0.6.1 is released
