### ISSUE TITLE
Memory not released upon service shudown

### ISSUE THREAD

**Issue by nosynose** [pact-foundation/pact-reference#5]
Hi,

The cli's doc says

"Shutdown the mock server by id or port number, releasing all its resources."

It appears to me that it does not release the memory when a service is shutdown. With the moderate 3 operation pact file I have, the memory grows by about 15 MB / service. The tool runs out of memory eventually.

**Comment by uglyog** [comment]
This is an issue with Hyper. I am calling close on the listener, but this does not currently work and the resources will not be released until the process exits. See https://github.com/hyperium/hyper/issues/338

I'll have a look to see if there is any other memory leaks.

**Comment by Mastermindaxe** [comment]
Is this fixed?

**Comment by alilleybrinker** [comment]
It looks like Hyper fixed the issue with version 0.11 (Hyper is now at version 0.13). `pact_server_cli` uses Hyper version 0.9, and the fix wasn't backported, so the only way to fix it would be to upgrade Hyper (which is not trivial, as changes between versions may be substantial, and more recent changes to adapt to the standardization of `Future`s and async/await have been very substantial).

**Comment by uglyog** [comment]
The core mock server (the one that responds based on the contents of a Pact file) has already been upgraded to Hyper 0.13 by @audunhalland. See releases https://github.com/pact-foundation/pact-reference/releases/tag/libpact_mock_server-v0.5.0 and https://github.com/pact-foundation/pact-reference/releases/tag/libpact_mock_server-v0.7.0. 

I'm currently working on upgrading the CLI master server (one that controls the other mock servers).

**Comment by uglyog** [comment]
Closing this as all mock servers are running on Hyper 0.13
