### ISSUE TITLE
Unable to run pact_mock_server_cli from Jenkins pipeline job

### ISSUE THREAD

**Issue by liqincao** [pact-foundation/pact-reference#6]
On the same Linux machine, I can run pact_mock_server_cli from commandline but it throws the following exception when running from a Jenkins job.  From the stacktrace, the problem seems to be related to TermLogger::new.  Even when loglevel is none, the loggers are still initialized.  Two questions:

1. Is TermLogger required for pact_mock_server_cli?
2. If not, can we completely disable logging?

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:323
stack backtrace:
   1:     0x7f39193309ba - std::sys::imp::backtrace::tracing::imp::write::h917062bce4ff48c3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7f391933608f - std::panicking::default_hook::{{closure}}::h0bacac31b5ed1870
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x7f3919333f56 - std::panicking::default_hook::h5897799da33ece67
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x7f3919334607 - std::panicking::rust_panic_with_hook::h109e116a3a861224
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x7f3919334494 - std::panicking::begin_panic::hbb38be1379e09df0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x7f39193343b9 - std::panicking::begin_panic_fmt::h26713cea9bce3ab0
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x7f3919334347 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:373
   8:     0x7f391937298d - core::panicking::panic_fmt::hcfbb59eeb7f27f75
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:69
   9:     0x7f39193728c4 - core::panicking::panic::hd383cb12a44b01ff
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/panicking.rs:49
  10:     0x7f3918d113cb - <core::option::Option<T>>::unwrap::h11b9ffa75dcc8a09
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/macros.rs:21
  11:     0x7f3918d183fc - simplelog::termlog::TermLogger::new::h76d41829e4c65821
                        at /home/ddclnx03/snap/szeng/.cargo/registry/src/github.com-1ecc6299db9ec823/simplelog-0.1.0/src/termlog.rs:60
  12:     0x7f3918c16a1e - pact_mock_server_cli::setup_loggers::h94812a7b74707d2d
                        at /home/szeng01/pact/rust/pact_mock_server_cli/src/main.rs:81
  13:     0x7f3918c185ac - pact_mock_server_cli::handle_command_args::h82ea34bb8622116c
                        at /home/szeng01/pact/rust/pact_mock_server_cli/src/main.rs:225
  14:     0x7f3918c1730c - pact_mock_server_cli::main::h5b29e1e8e212167f
                        at /home/szeng01/pact/rust/pact_mock_server_cli/src/main.rs:116
  15:     0x7f391933db6a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  16:     0x7f3919335025 - std::rt::lang_start::hd661476ce2fc2931
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  17:     0x7f3918c1dc02 - main
  18:     0x7f3917ef6b34 - __libc_start_main
  19:     0x7f3918b66018 - <unknown>
  20:                0x0 - <unknown>

**Comment by uglyog** [comment]
I think a logger has to be setup, or the log statements littered throughout the code will fail.

We have a few options here.

1. I'll upgrade the simple_log crate and see if that resolves the issue. Looks like v0.3.0 fixes the option unwrap issue.

2. Introduce a command line flag to not log to stdout.

3. If logging is set to none, then use a null logger. But you are probably going to need the log to work out why things don't verify correctly.

I think I'll do 1 and 2, that should give you the control you need.

**Comment by liqincao** [comment]
Great!  Thank you!

**Comment by uglyog** [comment]
I've released v0.2.2 with this fix in

**Comment by liqincao** [comment]
Hi Ronald,

Now I’m getting a different exception when running with or without –no-console-log flag: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Term', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:868

/var/lib/jenkins/workspace/cricket-product-order-ms@script/productorder-tests-pact/pact-mock-server-cli/linux/pact_mock_server_cli v0.2.3
Standalone Pact mock server

USAGE:
    pact_mock_server_cli [FLAGS] [OPTIONS] <SUBCOMMAND>

FLAGS:
        --help              Prints help information
        --no-console-log    Do not log to the console via standout out
        --no-file-log       Do not log to an output file
    -v, --version           Prints version information

OPTIONS:
    -h, --host <host>            hostname the master mock server runs on (defaults to localhost)
    -l, --loglevel <loglevel>    Log level for mock servers to write to the log file (defaults to info) [values: error,
                                 warn, info, debug, trace, none]
    -p, --port <port>            port the master mock server runs on (defaults to 8080)

SUBCOMMANDS:
    create      Creates a new mock server from a pact file
    help        Prints this message or the help of the given subcommand(s)
    list        Lists all the running mock servers
    shutdown    Shutdown the mock server by id or port number, releasing all its resources
    start       Starts the master mock server
    verify      Verify the mock server by id or port number, and generate a pact file if all ok
/var/lib/jenkins/workspace/cricket-product-order-ms@script/productorder-tests-pact/pact-mock-server-cli/linux/pact_mock_server_cli v0.2.3
pact mock server version  : v0.2.3
pact specification version: v2.0.0

==============================================================================================================
Start a pact mock service with /var/lib/jenkins/workspace/cricket-product-order-ms@script/productorder-tests-pact/target/pacts/ProductOrder-ProductCatalog.json
==============================================================================================================
++ /var/lib/jenkins/workspace/cricket-product-order-ms@script/productorder-tests-pact/pact-mock-server-cli/linux/pact_mock_server_cli create -p 9000 -f /var/lib/jenkins/workspace/cricket-product-order-ms@script/productorder-tests-pact/target/pacts/ProductOrder-ProductCatalog.json
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Term', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:868
stack backtrace:
   1:     0x7fdf1de15fdc - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x7fdf1de196be - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x7fdf1de192c4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x7fdf1de19b5b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x7fdf1de199f4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x7fdf1de19919 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x7fdf1de198a7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x7fdf1de4693d - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x7fdf1dc216c5 - core::result::unwrap_failed::hf12289fcbaf0ad5a
  10:     0x7fdf1dc3ce3d - pact_mock_server_cli::handle_command_args::hc84f30a186861620
  11:     0x7fdf1dc36855 - pact_mock_server_cli::main::h8304d65a66caaf97
  12:     0x7fdf1de20aaa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  13:     0x7fdf1de1a2c6 - std::rt::lang_start::hd7c880a37a646e81
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/rt.rs:57
  14:     0x7fdf1cdcdb34 - __libc_start_main
  15:     0x7fdf1dc13ef8 - <unknown>
  16:                0x0 - <unknown>
+ output=
+ set +x

**Comment by uglyog** [comment]
Oops, I only fixed the start command.

I've now renamed the `--no-console-log` argument to `--no-term-log`, and for the other commands switch to a simple logger if it is set. v0.2.3 has this change.

**Comment by liqincao** [comment]
It’s working great!  Thanks!
