### ISSUE TITLE
Loose checking of HTTP status range

### ISSUE THREAD

**Issue by uglyog** [pact-foundation/pact-reference#63]
See https://github.com/pact-foundation/pact-specification/issues/68

**Comment by mefellows** [comment]
So just thinking of the consumer DSL.

Does it make sense to modify the DSL to accept a list of pre canned ranges (grouped by the standard response ranges below)

* Informational responses (100–199): `informational(100)`
* Successful responses (200–299): `success(200)`
* Redirects (300–399): `redirect(301)`
* Client errors (400–499): `clientError(400)`
* Server errors (500–599): `serverError(500)`

Or supply ranges. 

E.g.

**Option 1:** 
```
      let alice_service = PactBuilder::new("Consumer", "Alice Service")
        // Start a new interaction. We can add as many interactions as we want.
        .interaction("a retrieve Mallory request", |i| {
          // Defines a provider state. It is optional.
          i.given("there is some good mallory");
          // Define the request, a GET (default) request to '/mallory'.
          i.request.path("/mallory");
          // Define the response we want returned.
          i.response
            .informational(<optional example status>) // matches 20x, default example 200
            .content_type("text/plain")
            .body("That is some good Mallory.");
        })
```

**Option 2: specify a range**
```
          i.response
            .status([200..209], <optional example status>) // Matches 20x, default example 200
            .content_type("text/plain")
            .body("That is some good Mallory.");
```

**Option 3: Specify a list of values**
```
          i.response
            .status([200, 201], <optional example status>) // Matches 200, 201, default example of 200
            .content_type("text/plain")
            .body("That is some good Mallory.");
```

Under the hood, the matching rules would probably have to evaluate ultimately to (3) anyway. But just thinking about the main use case. I suppose, we could supply multiple?

**Comment by mefellows** [comment]
Second thing is the Matcher itself. 

From a Rust perspective, I'm assuming we need to create a new `MatchingRule`, because existing ones aren't likely to work. I suppose it _could_ map to the `Regex` rule, but wondering if an `Include(Vec<usize>)` would be clearer?

The second part of this is contract serialisation and updating the v4.0 spec draft, specifically https://github.com/pact-foundation/pact-specification/tree/version-4#supported-matchers

I'm wondering if perhaps an "Includes" matcher makes sense here. Something like this:

```
{ "match":"includes", "values": [200, 201, 202] }
```

This could generalise a bit better to enum like fields, which currently have to be specified as a regex.

**Comment by uglyog** [comment]
All three options would be good. 

The best option would be to create a new type of matcher. The includes one works on strings, so you would need to change it's behaviour. Something like a `MustBeOneOf` matcher might be a better idea.

We won't need to create this as part of V4, as we are not changing the pact file format.

**Comment by mefellows** [comment]
Thanks Ron. How would be translate the Rust matcher to a specification matcher - a regex matcher?

**Comment by uglyog** [comment]
No, we add a totally new one. Once it's done I'll port it over to Pact-JVM. And then we can update the Pact-JS DSL to support it.

**Comment by mefellows** [comment]
> We won't need to create this as part of V4, as we are not changing the pact file format.

Ah, I read the above as we didn't need a new matcher. But because this is backwards compatible we can do it?

**Comment by uglyog** [comment]
The implementations just ignore matchers they don't know about

**Comment by TimothyJones** [comment]
So, I think there's a bit more to this - it's kind of the reverse of the typical loose matching. If the client is saying "hey, I'll accept any response code from <this list> for this response", we might want to run the consumer test multiple times to assert that the client handles all of them. On the provider side, we'll want to say "does the response code we actually get match any of these?"

At first I was hoping we could do it entirely in the client side DSL ("run this test repeatedly mocking different response codes"), but then we'd end up with an impossible contract for the provider, where all response codes were expected.

**Comment by uglyog** [comment]
I don't think running the consumer test multiple times to assert that the client handles all of them is what we are trying to do here. You can use a unit test for that.

Most of the time the response code has meaning, and so you would have a different contract test for each one.

However, I can see the following case:
* Provider gets a POST with JSON and returns:
  * 200 OK if the entity was updated (maybe with the updated JSON)
  * 201 CREATED if a new entity was created
  * 204 NO CONTENT if the update resulted in a no-op

In this case, the consumer could not care which particular response code was returned, as long as it was a success. I still believe those should be separate contract tests, but I also believe in not being prescriptive.

**Comment by TimothyJones** [comment]
Hmm. I agree that those are separate contract tests (even if they result in the same code path in the consumer), and I don't feel like that's being too prescriptive.

The reason I'd like this feature is for error codes - for the consumer to be able to say "well, I can handle all these types of errors", without needing to say "I'd like you to be able to produce all these types of errors, please".

**Comment by mefellows** [comment]
There's nothing stopping us from doing that in the JS DSL as you state, Tim. Worth thinking about re: the conversation we had the other day.

**Comment by TimothyJones** [comment]
Ah, but if we do that in the DSL, the multiple iterations will end up in the contract, which we don't want :)

**Comment by mefellows** [comment]
Ah! But, (and spitballing future capability here of course), the consumer side could repeat the test for each variant, but only generate a single matcher for provider side validation e.g. `{ "match":"includes", "values": [200, 201, 202] }`.

This would be much better. And, we could do the _same thing_ for other optionals - so the "may be null or something" is actually safe now, because both variants are tested by the consumer.

**Comment by uglyog** [comment]
Implemented as part of V4
