### ISSUE TITLE
(Rust) Inconsistent type returned for `actual` and `expected` mismatches

### ISSUE THREAD

**Issue by surpher** [pact-foundation/pact-reference#64]
## Context

When calling `mock_server_mismatches` the types of `actual` and `expected` keys in mismatches array are inconsistent.

Using Rust `pact_mock_server_ffi` for use with Swift/iOS.
Changed the `rust/pact_matching/Cargo.toml` and set `onig = 4.3.3` to be able to build on my system. Onig 5.0 fails to compile. 🤷‍♂️

macOS 10.15.4
clang and other needed tools to compile were installed using homebrew.

Example: 
- when expected query parameter is not present in the actual request, then `actual` and `expected` values are returned as a `String`.
- when expected body does not match actual body, then the `actual` and `expected` values are returned as an `Array<Int>`.

## Steps to reproduce

Set Mock Server expectation:

- `POST /path`
- body: `{"foo": "bar"}`

Run API client that sends the following request:

- `POST /path`
- headers: `"Content-Type": "application/json"`
- body: `{\n\n}`

## Expectation:

When fetching mismatches by calling `mock_server_mismatches(socketAddress)` 
Then Mock Server should respond with:

```
[
... // key:values
        "mismatches": [
            "mismatch": "Expected entry foo=bar but was missing",
            "type": "BodyMismatch",
            "path": "$"
        ]
... // key:values
]
```

## Observed behaviour:

When fetching mismatches by calling `mock_server_mismatches(socketAddress)` 
Then Mock Server responds with:

```
[	
	{
    "method": "POST",
    "mismatches": [
      {
        "actual": [123,125],
        "expected": [123,34,102,111,111,34,58,34,98,97,114,34,125],
        "mismatch": "Expected a Map with 1 elements but received 0 elements",
        "path": "$",
        "type": "BodyMismatch"
      },
      {
        "actual": [123,125],
        "expected": [123,34,102,111,111,34,58,34,98,97,114,34,125],
        "mismatch": "Expected entry foo=bar but was missing",
        "path": "$",
        "type": "BodyMismatch"
      }
    ],
    "path": "/user",
    "type": "request-mismatch"
  }
]
```

**Comment by uglyog** [comment]
JSON will now look like

```json
{
  "method": "POST",
  "mismatches": [
    {
      "actual": "\"no-very-bar\"",
      "expected": "\"bar\"",
      "mismatch": "Expected 'bar' to be equal to 'no-very-bar'",
      "path": "$.foo",
      "type": "BodyMismatch"
    }
  ],
  "path": "/path",
  "type": "request-mismatch"
}
```

**Comment by surpher** [comment]
Just tested with FFI `v0.0.2` and it works as expected. This issue can be closed.
