### ISSUE TITLE
Start mock server using HTTPS

### ISSUE THREAD

**Issue by surpher** [pact-foundation/pact-reference#65]
## Suggestion

When starting up Mock Server the FFI function could take a flag to defining whether to start the server using `https` or `http` (eg: `create_mock_server(pact, port, protocol = standard)`)

Or a new explicit FFI function to start Mock Server using `https` (eg: `create_ssl_mock_server(pact, port)`)

## Context

During development of [`surpher/pact-swift`](https://github.com/surpher/pact-swift) it was found that reaching Mock Server over `https` was not behaving as expected even when setting the API client to ignore self-signed certificates. 

Apple platforms (such as iOS) strongly encourage network requests to be made over `https` by default! Any decent Swift developer only provides the domain name to the API provider without defining the transfer protocol in the URL string, but sets the `component.scheme` for **all** network calls, which is immutable at the caller side (eg: `makeNetworkRequest(url: "domain.com/path/to/resource/", completion: { ... } )` - caller _should_ not be allowed to change the transfer protocol.

This means anyone using `pact-swift` to test their API client making network requests over `https` would need to refactor their "secure" API client implementation to handle "insecure" connections to 0.0.0.0. They would also need to define exceptions in the system configuration files to let Apple know why they are allowing insecure network requests, etc.

**Comment by uglyog** [comment]
I've gone with the simplest approach to begin with, adding a boolean flag to the `create_mock_server` function.

`create_mock_server(pact, port, true)` for starting with HTTPS.

**Comment by surpher** [comment]
I've just successfully ran it against my implementation of `swift-pact` and it works just fine.

**Comment by surpher** [comment]
This has been [tested](https://github.com/surpher/pact-swift-examples/blob/master/Pact-iOS-Example/Pact-iOS-ExampleTests/Pact_iOS_ExampleTests.swift#L79) with using FFI `v0.0.2` and works as expected.

This issue can be closed.
