### ISSUE TITLE
Auto-generated header file complains with Typedef redefinition errors

### ISSUE THREAD

**Issue by surpher** [pact-foundation/pact-reference#66]
## Context

When using the `pact_mock_server_ffi` in an iOS project, I ran `cbindgen src/lib.rs -l c > pact_mock_server.h` command to auto-generate a header file.

The generated header file and `libpact_mock_server.a` are imported into Xcode project and compiler knows how to interact with the lib.

When imported into Xcode, compiler complains with invalid type redefinition errors.

Environment: 

- macOS: 10.15.4
- Xcode: 11.4
- Command Line Tools: Xcode 11.4 (11E146)
- Rust / Pact Mock Server commit: da885a3c68a750eabb10f1f23832254af484542e

## Steps to reproduce

1. `cd` to `./pact-reference/rust/pact_mock_server_ffi`
2. run `cbindgen src/lib.rs -l c > pact_mock_server.h`
3. add the following to end of `Cargo.toml` file:
```text
[lib]
name = "pact_mock_server"
crate-type = ["staticlib", "cdylib"]
```
4. run `cargo lipo --release` # (probably not required)
5. _Add_ `pact_mock_server.h` and lib file to an Xcode project

## Expected

No compile time errors

## Actual

Header file defines two `enum` types with same signature (apart from at the tail end of enum declaration) and 

```swift
/* pact_mock_server.h */
// Lines 6 - 18:
...
/**
 * Request or Response enum
 */
typedef enum {
  /**
   * Request part
   */
  Request,
  /**
   * Response part
   */
  Response,
} InteractionPart;

// Lines 60 - 72
/**
 * Result of generating a value from a regex
 */
typedef enum {
  /**
   * Was generated OK
   */
  Ok, // ERROR: Redefinition of enumerator `Ok`
  /**
   * There was an error generating the string
   */
  Failed, // ERROR: Redefinition of enumerator `Failed`
} RegexResult_Tag;
```

## Workaround

Manually editing the `pact_mock_server.h` file to DRY up the `enum`s into a single `Result` enum type and using that one in places where previously re-defined types were used (and complaining):
```swift
typedef enum Result_Tag_ {
  /**
   * Was generated OK
   */
  Ok,
  /**
   * There was an error generating the string
   */
  Failed,
} Result_Tag;
```

## Possible solution

Re-use type definition where enum's list of cases is the same.

## Reference

![Screen Shot 2020-05-01 at 2 26 52 pm](https://user-images.githubusercontent.com/1733327/80782014-d8280980-8bb7-11ea-9a41-6199d39af010.png)

**Comment by uglyog** [comment]
Oh, dammit :-D

So we could never have two different enums that happen to have the same variant name!

In this case, I think a single result struct will work because they all all returning strings.

**Comment by surpher** [comment]
FFI `v0.0.2` used with the generated header file. Works as expected.

This issue can be closed.
