### ISSUE TITLE
Support messages in rust verifier for specification v3.0

### ISSUE THREAD

**Issue by dallagi** [pact-foundation/pact-reference#73]
The version 3.0 of the pact specification introduces support for messages, as documented [here](https://github.com/pact-foundation/pact-specification/tree/version-3#introduces-messages-for-services-that-communicate-via-event-streams-and-message-queues).

However, the reference implementation of the verifier for the v3.0 specification does not appear to support messages.
When run against a v3 pact, the output is as follows:

```
Verifying a pact between <consumer> and <provider>
         WARNING: Pact file has no interactions
```

Looking at the code - even though I'm not really fluent in Rust - it looks like it only supports "standard" interactions.

In case it may be helpful, the example contract I was trying to validate via the cli verifier can be found [here](https://gist.github.com/dallagi/fb5bb1a9c01d14a468e9d180d99bcf14)

Thank you!

**Comment by uglyog** [comment]
Message support was added with #74

**Comment by dallagi** [comment]
I just tested this functionality and indeed it works perfectly. Thanks a lot!
