### ISSUE TITLE
libpact_mock_server fails to write description of an interaction

### ISSUE THREAD

**Issue by surpher** [pact-foundation/pact-reference#75]
# 🌎 Environment

 - Xcode: Xcode 11.7
 - Platform: macOS + rust (ffi) + swift
 - Version/Release: pactRust (0.7.2) (d3c5cf28)

# 💬 Description

Using `libpact_mock_server.a` [built from ffi](https://gist.github.com/surpher/bbf88e191e9d1f01ab2e2bbb85f9b528) on` master` and used with PactSwift framework to run pact tests in Swift, the interaction descriptions passed to `libpact_mock_server.a` to be written into a pact file are ignored.

This happens if there is one interaction or many, where every interactions' descriptions in the generated file are the same.

# 🦶 Reproduction Steps

1. Build `lippact_mock_server.a` running `cargo lipo --release` in the ffi folder
2. Generate header file from the same ffi version using ` cbindgen src/lib.rs -l c > pact_mock_server.h`
3. Move binary and header file to PactSwift project
4. Set `PACT_OUTPUT_DIR: $(PROJECT)/pacts` environment var in `PactSwift-iOS` schema's Run attributes
5. Set `PACT_LOGGING_LEVEL: debug` environment var in `PactSwift-iOS` schema's Run attributes
6. Run PactSwift tests - focused on `MockServiceTests.testMockService_Writes_PactContract`
7. Observe PactSwift generated JSON sent to `libpact_mock_server` and file written by `libpact_mock_server`

# 🤔 Expected Results

Generated Pact file contains one interaction with description `"description": "Request for list of users"`

# 😲 Actual Results

Generated Pact file contains one interaction with description `"description": "Interaction 0"`

## 🌳 Logs

Pact JSON sent to `libpact_mock_server.a`:
```json
{
	"metadata": {
		"pactSpecification": {
			"version": "3.0.0"
		},
		"pact-swift": {
			"version": "0.0.0"
		}
	},
	"interactions": [{
		"interactionDescription": "Request for list of users",
		"response": {
			"status": 200,
			"body": {
				"baz": [123],
				"foo": "bar"
			},
			"generators": {
				"body": {}
			},
			"matchingRules": {
				"body": {
					"$.baz": {
						"matchers": [{
							"match": "type",
							"max": 5,
							"min": 1
						}]
					},
					"$.foo": {
						"matchers": [{
							"match": "type"
						}]
					}
				}
			}
		},
		"providerState": "users exist",
		"request": {
			"path": "/user",
			"method": "get"
		}
	}],
	"provider": {
		"name": "unit-test-api-provider"
	},
	"consumer": {
		"name": "pactswift-unit-tests"
	}
}
```

Pact JSON written into a pact file by `libpact_mock_server.a`:
```json
{
  "consumer": {
    "name": "pactswift-unit-tests"
  },
  "interactions": [
    {
      "description": "Interaction 0",
      "providerStates": [
        {
          "name": "users exist"
        }
      ],
      "request": {
        "method": "GET",
        "path": "/user"
      },
      "response": {
        "body": {
          "baz": [
            123
          ],
          "foo": "bar"
        },
        "matchingRules": {
          "body": {
            "$.baz": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "type",
                  "max": 5,
                  "min": 1
                }
              ]
            },
            "$.foo": {
              "combine": "AND",
              "matchers": [
                {
                  "match": "type"
                }
              ]
            }
          }
        },
        "status": 200
      }
    }
  ],
  "metadata": {
    "pact-swift": {
      "version": "0.0.0"
    },
    "pactRust": {
      "version": "0.7.2"
    },
    "pactSpecification": {
      "version": "3.0.0"
    }
  },
  "provider": {
    "name": "unit-test-api-provider"
  }
}
```

## 📄 Stack Traces

```
n/a
```

# 🤝 Relationships

- Related PRs or Issues:

**Comment by uglyog** [comment]
Found the issue. The interaction description should be `description` not `interactionDescription` in the JSON sent to the mock server. The mock server is not finding the description attribute, so it is assigning a default one.

Looking at https://github.com/surpher/PactSwift/blob/master/Sources/Services/MockServer.swift#L78, the sequence is wrong. It is calling `shutdownMockServer` which shuts the mock server down and removes it, then calls `create_mock_server` which creates a new one, and then calls `writePactContractFile`.

The sequence should be first `writePactContractFile` to get the mock server to write it out, and then `shutdownMockServer`.

**Comment by surpher** [comment]
Ah, thanks for pointing out the unexpected attribute! Odd how that seemed to have been working in previous versions. I'll fix it in PactSwift.

Regarding starting/shutting down, if memory still serves me, I had to fiddle around with the writing/shutting down mock server due to sandboxing in Swift/macOS/Xcode-land. I will revisit the area and see how it can be improved.
