### ISSUE TITLE
Updates to existing matchers are not reflected in the pact file

### ISSUE THREAD

**Issue by surpher** [pact-foundation/pact-reference#77]
# 🌎 Environment

 - Platform: iOS / PactSwift / libpact_mock_server_ffi built from cbb6e209
 - Version/Release: `master` branch
 - Dependency manager: Carthage 0.38

# 💬 Description

When writing a pact test and describing a value in body using an updated matcher, the change to that matcher is not reflected in the pact file. And if the pact file is deleted before running updated again, then the update is reflected in the pact file. 

# 🦶 Reproduction Steps

1. Setup a pact test environment using PactSwift ([unit test for this issue](https://github.com/surpher/PactSwift/blob/master/Tests/MockServiceTests.swift#L388)).
2. Write a pact test where `.willRespondWith(body:)` contains a matcher:
```swift
.willRespondWith(body: [
  "related": EachLike("https://someurl.com/entity/related", min: 0, max: 5)
]
```
3. Run unit test
4. Inspect test Pact file in `$PROJECT_DIR/tmp/pacts` to contain `"matchingRules"` object for:
```json
...
"body": {
  "$.related": {
    "combine": "AND",
    "matchers": [
       {
           "match": "type",
           "max": 5,
           "min": 0
        }
    ]
  },
...
```
5. Update matcher's `min:` and `max:` to different values (eg.):
```swift
.willRespondWith(body: [
  "related": EachLike("https://someurl.com/entity/related", min: 1, max: 10)
]
```
6. Run unit test again
7. Inspect the written pact file and observe the `min:` and `max:` for the used matcher.

Note: Tried with other matchers too, eg., replace `EachLike` with `SomethingLike` ("type").

# 🤔 Expected Results

When changing the matcher, the changes to the matcher values are written to the pact file:

```json
...
"body": {
  "$.related": {
    "combine": "AND",
    "matchers": [
       {
           "match": "type",
           "max": 10,
           "min": 1 
        }
    ]
  },
...
```

# 😲 Actual Results

The changes to `min:` and `max:` are not reflected in the pact file and remain set to `max: 5` and `min: 0`

## 🌳 Logs

```
Attached ZIP file contains:
01-Pact-for-libpact_mock_server_ffi.json - Pact object sent to `create_mock_server(pact,...)
02-Pact-Written-by-libpact_mock_server_ffi.json - Pact written to `./tmp/pacts` folder by libpact_mock_server_ffi
03-Pact-for-libpact_mock_server_ffi.json - Pact object sent to `create_mock_server(pact,...)
04-Pact-Written-by-libpact_mock_server_ffi.json - Pact written to `./tmp/pacts` folder by libpact_mock_server_ffi
```

[provided_pact-written_pact.zip](https://github.com/pact-foundation/pact-reference/files/5360618/provided_pact-written_pact.zip)

# ⑂ Possible workaround(s)

Manually removing the existing Pact file before running unit test suite.

**Comment by mefellows** [comment]
Yeah, I recall running into this one also. My recollection, which may be incorrect, is that the pact file _should_ be removed prior to running the tests - this implied feature has the benefit of allowing multiple tests to run in parallel or across a suite of files - but it has the drawback of not being obvious, which way result in badness.

So we should first clarify this is intended, and document it if that's the desired behaviour. Alternatively, we create a flag as per the current Ruby CLI.

**Comment by uglyog** [comment]
This feels like a defect to me, I would expect the Pact file to be correctly updated. I think the issue is the merging logic does not take matchers into account, and so probably thinks the Pact has not changed.

**Comment by uglyog** [comment]
Only needed a tiny fix:

```diff
            .map(|either| match either {
              Left(i) => i,
              Right(i) => i,
-             Both(i, _) => i
+             Both(_, i) => i
            })
```

:-D

**Comment by surpher** [comment]
Sorry it took me so long, but just confirmed the changes to existing matcher are reflected in the written file. 👍
