### ISSUE TITLE
Enhancement: allow user to specify the port of a mock server

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-reference#8]
I'm creating a Dockerised version of the CLI in order to stand up a mock dependency for several APIs.

Aside from having to issue multiple commands to make this happen (i.e. `pact-mock-server start && pact-mock-server create --file foo.json`), I can't control the port that the mock API starts on, which I need to know before starting the original docker container.

Having control of this should simplify configuration, as it's not easy to open a new port on a running Docker container in a portable way.

**Comment by uglyog** [comment]
The `create` command does an HTTP POST to the server created with `start`, so I don't think it should be included in the docker start script.

For the JVM mock server, we were able to specify a port range and make that range exposed via docker. The only other way would be to get the master server to proxy requests via a path prefix.

But we could build an mock server implementation that would work from within a docker container, similar to https://github.com/uglyog/pact-stub-server

**Comment by mefellows** [comment]
Yeah the create script would either be a command (in an ephemeral container) or issued at the server.

That stub server looks to be what I'm after anyway, so perhaps I should be using it. That opens up a few questions for me:

1. What are the main goals of each of the projects? (they seemingly overlap a lot)
2. The stub server uses the word 'verify' a lot - is it actually verifying the requests, or just serving them?

**Comment by uglyog** [comment]
Oops, the docs on the stub server are wrong. It does not do any verification.

So, the mock server is a proper pact mock server, supporting all the matching rules.

The stub server is just used to create a HTTP server that will return responses defined in pact files.

**Comment by mefellows** [comment]
Perfect - I'll close this off :)
