### ISSUE TITLE
Bug: MockServer build failing after MacOS (Big Sur) update

### ISSUE THREAD

**Issue by surpher** [pact-foundation/pact-reference#82]
Originally reported at https://github.com/surpher/PactSwift/issues/62

# 🌎 Environment

 - Xcode: 12.3
 - Platform: iOS 14.3
 - Version/Release: 0.3.4/0.3.5
 - Dependency manager: SPM

# 💬 Description

I was able to successfully setup PactSwift into my project. After the last MacOS update, the mockserver rust build, which is done as described in the docs through a script build phase, fails.

I updated rust/rustup and cargo-lipo to the newest version, even reinstalled them.

# 🦶 Reproduction Steps

MacOS 11.1 & build for ios (x86_64-apple-darwin)

1. Run Test build which executes the [`build-spm-dependency ios`](https://github.com/surpher/PactSwift/blob/main/Scripts/BuildPhases/build-spm-dependency) script
2. Observe the error

# 🤔 Expected Results

Successful build of the libpact_mock_server.a file 

# 😲 Actual Results

Error during rust build

## 🌳 Logs

```
error: linking with `cc` failed: exit code: 1
[...]
= note: ld: library not found for -lSystem
             clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## 📄 Stack Traces

`N/A`

# 🤝 Relationships

- Related PRs or Issues: #xxx, #yyy

**Comment by uglyog** [comment]
Big Sur has another victim

**Comment by surpher** [comment]
I'll look into a workaround where I could build on macOS 10.15 (GitHub Actions maybe) and share the binaries as artefacts. At least until compilers and toolchains catch-up with BigSur and Apple Silicon.

**Comment by surpher** [comment]
Turns out it is a linking problem and `env` issue when running scripts in Xcode's Build Phase.

Not a bug. 👍
