### ISSUE TITLE
pacts are shown as verified but the single interactions have the status "unknown"

### ISSUE THREAD

**Issue by individual-it** [pact-foundation/pact-reference#92]
I can upload and tag pacts also the verification from the provider seems to work. The dashboard on pactflow.io shows me a successfully verified pact but when I browse in the details the verification status for every interaction is "unknown" 

![successfully verified pact](https://user-images.githubusercontent.com/2425577/106264874-551f0700-624e-11eb-9ff9-fffece975b3e.png)
![successful interactions listed as "unknown"](https://user-images.githubusercontent.com/2425577/106264879-56e8ca80-624e-11eb-95c2-5ab516dbd45e.png)

If only a part of the interactions are successful, the failed ones are correctly shown as failed but the successful again are marked "unknown"
![3](https://user-images.githubusercontent.com/2425577/106265043-96171b80-624e-11eb-9937-17755eb78ab2.png)

discussion at slack
https://pact-foundation.slack.com/archives/CLS16AVEE/p1611899283008800

CC @uglyog

**Comment by uglyog** [comment]
This should be fixed now with the latest pact-js V3 version

**Comment by individual-it** [comment]
works fine 
![image](https://user-images.githubusercontent.com/2425577/107346459-d008dd00-6aec-11eb-9fb7-aa2e170870c7.png)

I love the ticks, for me as colour-blind person colours alone are not enough, THX
