### ISSUE TITLE
feat: implement retries for the HTTP client

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-reference#94]
To increase the robustness of Rust and the libraries that wrap it, we should add an automatic retry mechanism to the HTTP client in case of intermittent issues with the broker.

The current JVM and Ruby implementations have an implemented this, and we can follow for guidance.

**Comment by mefellows** [comment]
👏

**Comment by mefellows** [comment]
Is this done now Ron?

**Comment by uglyog** [comment]
Looks like it.
